### ISSUE TITLE
hb-service events.js:292 error launch

### ISSUE THREAD

**Issue by Seenve** [oznu/homebridge-config-ui-x#1057]
Error launch

Logs:
Feb 03 21:01:46 us.seenve.ru systemd[1]: Starting Homebridge...
Feb 03 21:01:46 us.seenve.ru systemd[1]: Started Homebridge.
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]: [2/3/2021, 9:01:46 PM] [HB Supervisor] Homebridge Storage Path: /var/lib/homebridge
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]: [2/3/2021, 9:01:46 PM] [HB Supervisor] Homebridge Config Path: /var/lib/homebridge/config.json
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]: [2/3/2021, 9:01:46 PM] [HB Supervisor] Logging to /var/lib/homebridge/homebridge.log
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]: events.js:292
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:       throw er; // Unhandled 'error' event
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:       ^
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]: Error: Unknown system error -122: Unknown system error -122, write
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]: Emitted 'error' event on WriteStream instance at:
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:     at emitErrorNT (internal/streams/destroy.js:106:8)
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:   errno: -122,
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:   code: 'Unknown system error -122',
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]:   syscall: 'write'
Feb 03 21:01:46 us.seenve.ru hb-service.js[27644]: }
Feb 03 21:01:46 us.seenve.ru systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 03 21:01:46 us.seenve.ru systemd[1]: homebridge.service: Failed with result 'exit-code'.

Default config.json 

* **Node.js Version**: 14.15.4
* **NPM Version**: 6.14.10
* **Homebridge Version**: 1.1.7
* **Homebridge Config UI X Version**: 4.37.0
* **Operating System**: Ubuntu 18.04
* **Process Supervisor**: Systemd

**Comment by Seenve** [comment]
Problem solved.
I reinstalled fully homebridge.
