### ISSUE TITLE
4.39.0 requires CXXABI_1.3.9 which is not available in Centos 7

### ISSUE THREAD

**Issue by filibuster007** [oznu/homebridge-config-ui-x#1086]
homebridge-config-ui-x is not starting as it seems to rely on CXXABI_1.3.9  which is not available on Centos 7. 

**To Reproduce:**
Install 4.39.0 on a machine running Centos 7

**Expected behavior:**
Rely on the libs available in Centos 7 : 
nm -D /lib64/libstdc++.so.6 | grep CXXABI
0000000000000000 A CXXABI_1.3
0000000000000000 A CXXABI_1.3.1
0000000000000000 A CXXABI_1.3.2
0000000000000000 A CXXABI_1.3.3
0000000000000000 A CXXABI_1.3.4
0000000000000000 A CXXABI_1.3.5
0000000000000000 A CXXABI_1.3.6
0000000000000000 A CXXABI_1.3.7
0000000000000000 A CXXABI_TM_1

**Logs:**

[2/17/2021, 9:52:52 PM] [Homebridge UI] Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/prebuilds/linux-x64/node.abi83.node)
[2/17/2021, 9:52:52 PM] [Homebridge UI] [node-pty] Node.js v14.15.5
[2/17/2021, 9:52:52 PM] [Homebridge UI] [node-pty] Failed to load node-pty module
[2/17/2021, 9:52:52 PM] [Homebridge UI] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.
[2/17/2021, 9:52:52 PM] [Homebridge UI] [node-pty] Follow the steps below to resolve this issue.
[2/17/2021, 9:52:52 PM] [Homebridge UI] [node-pty] Failed to rebuild npm modules automatically. Manual operation is now required.
[2/17/2021, 9:52:52 PM] [Homebridge UI] [node-pty] From the terminal run this command to rebuild npm modules:

[2/17/2021, 9:52:52 PM] [Homebridge UI] sudo hb-service rebuild

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.15.5
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.1.7
* **Homebridge Config UI X Version**: 4.39.0
* **Operating System**: Centos
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by philhagen** [comment]
this seems to be the result of something in node-pty-prebuilt-multiarch but I'm not smart enough to get more details than even that tenuous idea...

**Comment by oznu** [comment]
For a quick fix delete this file (delete the one showing in the log):

```
/usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/prebuilds/linux-x64/node.abi83.node
```

And restart.

**Comment by philhagen** [comment]
Service is still unable to start after removing `/usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node`.  Now seeing the following messages in the log:
```
[2/18/2021, 5:43:53 AM] [Homebridge UI] Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/prebuild-loader.js
- /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
- /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
[2/18/2021, 5:43:53 AM] [Homebridge UI] [node-pty] Node.js v14.15.4
[2/18/2021, 5:43:53 AM] [Homebridge UI] [node-pty] Failed to load node-pty module
[2/18/2021, 5:43:53 AM] [Homebridge UI] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.
[2/18/2021, 5:43:53 AM] [Homebridge UI] [node-pty] Follow the steps below to resolve this issue.
[2/18/2021, 5:43:53 AM] [Homebridge UI] [node-pty] Failed to rebuild npm modules automatically. Manual operation is now required.
[2/18/2021, 5:43:53 AM] [Homebridge UI] [node-pty] From the terminal run this command to rebuild npm modules:

[2/18/2021, 5:43:53 AM] [Homebridge UI] sudo hb-service rebuild

[2/18/2021, 5:43:53 AM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: Node.js global modules rebuild required. See log errors above.
    at main (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:70826:19)
    at Object.1808 (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:70870:1)
    at __webpack_require__ (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:79135:42)
    at Object.8519 (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:63725:1)
    at __webpack_require__ (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:79135:42)
    at /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:79163:18
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:79164:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

running `hb-service rebuild` also re-adds the incompatible `pty.node` file.

**Comment by oznu** [comment]
Rollback for 4.38.0. I'll fix it properly in a new version - this won't happy for at least a week though.

**Comment by philhagen** [comment]
got it - can confirm that gets all back and operational.  also adding a note here for anyone finding this in the future that installing with the above `rpm` command also throws a `CXXABI_1.3.9` error, but it does not prevent proper functionality.

Thanks for your work on the project and help getting an interim fix so quickly!

**Comment by oznu** [comment]
Please try the test version:

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by filibuster007** [comment]
> Please try the test version:
> 
> https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

The test version (homebridge-config-ui-x v4.39.1-test.1) works on Centos 7.

**Comment by oznu** [comment]
Thanks for confirming!

**Comment by jvandijk** [comment]
I can confirm that this also solves the problem on Debian Jessie (running Homebridge on a Gen1 Unifi Cloud Key). 4.39.0 is not working, the 4.39.1-test.1 works.

**Comment by oznu** [comment]
v4.39.1 has now been released.

**Comment by filibuster007** [comment]
> v4.39.1 has now been released.

Can confirm that this release works as expected on Centos 7.
Many thanks for your work! Much appreciated!
