### ISSUE TITLE
Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by khusamov** [oznu/homebridge-config-ui-x#1088]
```
 [0;37m[2021-2-18 18:24:08] [0m[0;36m[Homebridge UI][0m [0;31mError: Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'
 Require stack:
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\xregexp\lib\index.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\decamelize\index.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@oznu\hap-client\dist\index.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\main.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\fork.js[0m
 [0;37m[2021-2-18 18:24:08] [0m[0;36m[Homebridge UI][0m [0;31mCaught Unhandled Rejection Error :: Details Below[0m
 Error: Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'
 Require stack:
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\xregexp\lib\index.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\decamelize\index.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@oznu\hap-client\dist\index.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\main.js
 - C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\fork.js
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
     at Module.require (internal/modules/cjs/loader.js:852:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at Object.<anonymous> (C:\Users\khusamov\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\xregexp\lib\index.js:3:30)
     at Module._compile (internal/modules/cjs/loader.js:959:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
     at Module.load (internal/modules/cjs/loader.js:815:32)
     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
     at Module.require (internal/modules/cjs/loader.js:852:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     'C:\\Users\\khusamov\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\xregexp\\lib\\index.js',
     'C:\\Users\\khusamov\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\decamelize\\index.js',
     'C:\\Users\\khusamov\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@oznu\\hap-client\\dist\\index.js',
     'C:\\Users\\khusamov\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\dist\\main.js',
     'C:\\Users\\khusamov\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\dist\\bin\\fork.js'
   ]
 }

```

**Comment by oznu** [comment]
Please provide more details. Open a new issue following the issue template.
