### ISSUE TITLE
Homebridge won't start after upgrading

### ISSUE THREAD

**Issue by biocross** [oznu/homebridge-config-ui-x#1107]
**Describe Your Problem:**
Updated `homebridge-ui` using the web interface, and now homebridge / homebridge-ui won't start. When I try to access the web ui, it says **refused to connect**.

**Logs:**

```
[01/03/2021, 06:56:26] [HB Supervisor] Starting Homebridge with extra flags: -I
[01/03/2021, 06:56:26] [HB Supervisor] Started Homebridge v1.2.5 with PID: 5645
[01/03/2021, 06:56:28] Loaded config.json with 0 accessories and 4 platforms.
[01/03/2021, 06:56:28] ---
[01/03/2021, 06:56:38] [HB Supervisor] OS: Linux 5.4.51-v7+ arm
[01/03/2021, 06:56:38] [HB Supervisor] Node.js v14.8.0 /usr/bin/node
[01/03/2021, 06:56:38] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[01/03/2021, 06:56:38] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[01/03/2021, 06:56:45] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/xregexp/lib/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/decamelize/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@oznu/hap-client/dist/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/xregexp/lib/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/xregexp/lib/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/decamelize/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@oznu/hap-client/dist/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
```

**Homebridge Config:**

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "------",
    "port": 51826,
    "pin": "-------"
  },
  "accessories": [],
  "platforms": [
    {
      "platform": "BelkinWeMo",
      "name": "WeMo Platform"
    },
    {
        "platform": "SensiboAC",
        "apiKey": "------"
    }
  ]
}
```

**Environment:**

* **Node.js Version**: v14.8.0
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.2.5
* **Homebridge Config UI X Version**: 4.39.1
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Steps taken:**
I've tried uninstalling and re-installing as mentioned in the README. I've also upgraded the node version.

**Comment by oznu** [comment]
What version of Node are you running after upgrading?

**Comment by biocross** [comment]
Node v14.8.0

**Comment by oznu** [comment]
v14.16.0 is the latest version of the 14x line up; v14.8.0 was never a supported LTS version.

Try upgrading with `sudo hb-service update-node`

**Comment by oznu** [comment]
Infact, your logs show you have two versions copies of Node.js installed.

One at `/usr/bin/node` and another at `/usr/local/bin/node` - this will cause no end of problems for you.

I'd recommend cleaning everything up and installing Node as per wiki instructions for your platform.

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux

Remove service:

```
sudo systemctl stop homebridge
sudo systemctl disable homebridge
sudo rm -rf /etc/systemd/system/homebridge.service
sudo systemctl daemon-reload
```

Remove all copies of Node.js and Homebridge:

```
sudo curl -fL https://git.io/JfFFM | sudo bash
```

Re-install Node.js as per wiki: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

Re-install any plugins.

**Comment by biocross** [comment]
Purging everything and re-installed worked. Thank you so much for your support!
