### ISSUE TITLE
Homebridge config ui x won't start after downgrade to node v8.8.0

### ISSUE THREAD

**Issue by Tapsel99** [oznu/homebridge-config-ui-x#1229]
/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

**Comment by oznu** [comment]
https://github.com/oznu/homebridge-config-ui-x#supported-nodejs-and-npm-versions
