### ISSUE TITLE
Homebridge-UI Issuing Reboot Commands

### ISSUE THREAD

**Issue by gdavids57** [oznu/homebridge-config-ui-x#1232]
**Describe The Bug:**

Without human initiation, Homebridge-UI issues Reboot commands to a running environment

**To Reproduce:**

I'm not able to reliably recreate the bug

**Expected behavior:**

The system, once up and running, should maintain this state until I command it to either Shutdown or Reboot

**Logs:**

```
[20/10/2021, 10:19:11] [HB Supervisor] OS: Linux 5.10.52+ arm
[20/10/2021, 10:19:11] [HB Supervisor] Node.js v14.17.4 /usr/local/bin/node
[20/10/2021, 10:19:11] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[20/10/2021, 10:19:11] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[20/10/2021, 10:20:45] [Homebridge UI] Homebridge Config UI X v4.41.2 is listening on :: port 8581
[20/10/2021, 10:20:56] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[20/10/2021, 10:21:16] [HB Supervisor] Starting Homebridge with extra flags: -I
[20/10/2021, 10:21:17] [HB Supervisor] Started Homebridge v1.3.5 with PID: 816
Initializing HAP-NodeJS v0.9.6...
[20/10/2021, 10:21:48] Loaded config.json with 1 accessories and 1 platforms.
[20/10/2021, 10:21:52] Loaded 0 cached accessories from cachedAccessories.
[20/10/2021, 10:21:52] ---
[20/10/2021, 10:21:58] [Homebridge UI] [npm] Failed to check registry.npmjs.org for updates: "timeout of 5000ms exceeded" - see https://git.io/JJSz6 for help.
[20/10/2021, 10:22:17] Loaded plugin: homebridge-blinds-servo@1.1.3
[20/10/2021, 10:22:17] Registering accessory 'homebridge-blinds-servo.ServoBlinds'
[20/10/2021, 10:22:17] ---
[20/10/2021, 10:22:18] Loaded plugin: homebridge-config-ui-x@4.41.2
[20/10/2021, 10:22:18] Registering platform 'homebridge-config-ui-x.config'
[20/10/2021, 10:22:18] ---
[20/10/2021, 10:22:18] Loading 1 platforms...
[20/10/2021, 10:22:18] [Config] Initializing config platform...
[20/10/2021, 10:22:18] [Config] Running in Service Mode
[20/10/2021, 10:22:18] Loading 1 accessories...
[20/10/2021, 10:22:18] [Blinds-01] Initializing ServoBlinds accessory...
Preparing Advertiser for 'Homebridge C6ED 0A0D' using bonjour-hap backend!
Setup Payload:
X-HM://0024SEW7KG09T
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 797-50-800 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge C6ED 0A0D' using bonjour-hap backend!
[20/10/2021, 10:22:20] Homebridge v1.3.5 (Homebridge C6ED) is running on port 51854.
[20/10/2021, 10:22:46] [Blinds-01] Moving down
[20/10/2021, 10:22:55] [Blinds-01] Success moving to 2
[20/10/2021, 10:23:01] [Blinds-01] Moving up
[20/10/2021, 10:23:06] [Blinds-01] Success moving to 71
[20/10/2021, 10:23:09] [Blinds-01] Moving down
[20/10/2021, 10:23:15] [Blinds-01] Success moving to 29
[20/10/2021, 10:23:24] [Blinds-01] Moving down
[20/10/2021, 10:23:28] [Blinds-01] Success moving to 3
[20/10/2021, 10:23:29] [Blinds-01] Moving up
[20/10/2021, 10:23:33] [Blinds-01] Success moving to 78
[20/10/2021, 10:23:37] [Blinds-01] Moving up
[20/10/2021, 10:23:41] [Blinds-01] Success moving to 80
[20/10/2021, 10:23:42] [Blinds-01] Moving down
[20/10/2021, 10:23:46] [Blinds-01] Success moving to 7
[20/10/2021, 10:23:47] [Blinds-01] Moving up
[20/10/2021, 10:23:51] [Blinds-01] Success moving to 8
[20/10/2021, 10:23:58] [Blinds-01] Moving up
[20/10/2021, 10:24:02] [Blinds-01] Success moving to 81
[20/10/2021, 10:24:05] [Blinds-01] Moving down
[20/10/2021, 10:24:09] [Blinds-01] Success moving to 44
[20/10/2021, 10:24:09] [Blinds-01] Moving down
[20/10/2021, 10:24:13] [Blinds-01] Success moving to 0
[20/10/2021, 10:24:53] [Blinds-01] Moving up
[20/10/2021, 10:24:57] [Blinds-01] Success moving to 86
[20/10/2021, 10:25:12] [Homebridge UI] Starting terminal session
[20/10/2021, 10:27:46] [Homebridge UI] Terminal session ended.
[20/10/2021, 10:30:52] [Blinds-01] Moving down
[20/10/2021, 10:30:56] [Blinds-01] Success moving to 6
[20/10/2021, 10:30:57] [Blinds-01] Moving up
[20/10/2021, 10:31:01] [Blinds-01] Success moving to 87
[20/10/2021, 10:31:29] [Homebridge UI] Rebooting linux server with command: "sudo -n shutdown -r now"
[20/10/2021, 10:31:31] [HB Supervisor] Stopping services...
[20/10/2021, 10:31:31] Got SIGTERM, shutting down Homebridge...
[20/10/2021, 10:31:36] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[20/10/2021, 10:33:04] [HB Supervisor] OS: Linux 5.10.52+ arm
[20/10/2021, 10:33:04] [HB Supervisor] Node.js v14.17.4 /usr/local/bin/node
[20/10/2021, 10:33:04] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[20/10/2021, 10:33:04] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[20/10/2021, 10:33:49] [Homebridge UI] Homebridge Config UI X v4.41.2 is listening on :: port 8581
[20/10/2021, 10:33:54] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[20/10/2021, 10:33:58] [Homebridge UI] TypeError: Invalid Version: undefined
[20/10/2021, 10:33:58] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/gt.js:2:29)
    at StatusService.checkHomebridgeStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71495:54)
    at StatusService.getHomebridgeStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71491:32)
    at StatusService.watchStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71461:53)
    at StatusGateway.serverStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71123:28)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at StatusGateway.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
    at WebSocketsController.pickResult (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/web-sockets-controller.js:86:24)
[20/10/2021, 10:34:14] [HB Supervisor] Starting Homebridge with extra flags: -I
[20/10/2021, 10:34:15] [HB Supervisor] Started Homebridge v1.3.5 with PID: 607
Initializing HAP-NodeJS v0.9.6...
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge C6ED",
        "username": "0E:4B:E7:D6:C6:ED",
        "port": 51854,
        "pin": "797-50-800"
    },
    "accessories": [
        {
            "name": "Blinds-01",
            "gpio_pin": 0,
            "servo_min": 2,
            "servo_max": 5,
            "servo_time": 2,
            "initial_position": 50,
            "relay_pin": 1,
            "move_cmd": "python3 /home/pi/adafruit_servo.py",
            "accessory": "ServoBlinds"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        }
    ]
}
```

**Screenshots:**

N/A

**Environment:**

* **Node.js Version**: v14.17.4
* **NPM Version**: v7.20.3
* **Homebridge Version**: v1.3.5
* **Homebridge Config UI X Version**: v4.41.2
* **Operating System**: Raspbian 10
* **Process Supervisor**: hb-service

**Comment by gdavids57** [comment]
There seems to be correlation between Homebridge coming up and a web session being active on a browser.  If there are no open sessions on either my Mac or my iPhone, Homebridge seems to start up just fine.  I'm going to try and recreate the "shut down scenario" while also monitoring the http traffic.
