### ISSUE TITLE
Can't install plugins... My homebridge is broken somehow?

### ISSUE THREAD

**Issue by Peterjuulk** [oznu/homebridge-config-ui-x#1242]
My homebridge is broken somehow. When I try to install plugins from the UI (only way I know) I get this error:

___

"TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

Command failed. Please review log for details."

___

Can anybody help a complete newbie.

BTW (I have thres plugins running in Homebridge already, and would like to not install, and set them up again.)

**Comment by spospordo** [comment]
I'm receiving the same message when attempting to install new plugins, or even updating the UI plugin. I've attempted restarting homeridge and my machine (pi). I have not located any other logs that have additional info.

**Comment by oznu** [comment]
This was fixed in the latest updated.

to fix you existing system see https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607
