### ISSUE TITLE
Updated homebridge-config-ui-x on Raspberry Pi, now Fastify is missing

### ISSUE THREAD

**Issue by rhymeswithmogul** [oznu/homebridge-config-ui-x#1352]
### Describe The Bug

I just installed Homebridge on a Raspberry Pi Model B, then logged in and updated the `homebridge-config-ui-x` plugin.  Now, it won't start.  It says that `fastify/lib/symbols` could not be found.

I tried to remove and re-add the plugin from the CLI, but `npm` is not installed.

### Logs

```text
[30/05/2022, 08:03:38] [HB Supervisor] OS: Linux 5.15.32+ arm
[30/05/2022, 08:03:38] [HB Supervisor] Node.js v16.15.0 /opt/homebridge/bin/node
[30/05/2022, 08:03:38] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[30/05/2022, 08:03:38] [HB Supervisor] UI Path: /var/lib/homebridge/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[30/05/2022, 08:05:27] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: Cannot find module 'fastify/lib/symbols'
Require stack:
- /var/lib/homebridge/node_modules/.pnpm/middie@6.0.0/node_modules/middie/index.js
- /var/lib/homebridge/node_modules/.pnpm/@nestjs+platform-fastify@8.4.4_u6bxr3c7htwmhq2t5wi3k6ht4y/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js
- /var/lib/homebridge/node_modules/.pnpm/@nestjs+platform-fastify@8.4.4_u6bxr3c7htwmhq2t5wi3k6ht4y/node_modules/@nestjs/platform-fastify/adapters/index.js
- /var/lib/homebridge/node_modules/.pnpm/@nestjs+platform-fastify@8.4.4_u6bxr3c7htwmhq2t5wi3k6ht4y/node_modules/@nestjs/platform-fastify/index.js
- /var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.45.0/node_modules/homebridge-config-ui-x/dist/main.js
- /var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.45.0/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/middie@6.0.0/node_modules/middie/index.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /var/lib/homebridge/node_modules/.pnpm/@nestjs+platform-fastify@8.4.4_u6bxr3c7htwmhq2t5wi3k6ht4y/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:266:58 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/lib/homebridge/node_modules/.pnpm/middie@6.0.0/node_modules/middie/index.js',
    '/var/lib/homebridge/node_modules/.pnpm/@nestjs+platform-fastify@8.4.4_u6bxr3c7htwmhq2t5wi3k6ht4y/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js',
    '/var/lib/homebridge/node_modules/.pnpm/@nestjs+platform-fastify@8.4.4_u6bxr3c7htwmhq2t5wi3k6ht4y/node_modules/@nestjs/platform-fastify/adapters/index.js',
    '/var/lib/homebridge/node_modules/.pnpm/@nestjs+platform-fastify@8.4.4_u6bxr3c7htwmhq2t5wi3k6ht4y/node_modules/@nestjs/platform-fastify/index.js',
    '/var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.45.0/node_modules/homebridge-config-ui-x/dist/main.js',
    '/var/lib/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.45.0/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
[30/05/2022, 08:05:27] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[30/05/2022, 08:05:27] [HB Supervisor] Stopping services...
```

### Config

```json
{
    "bridge": {
        "name": "Homebridge 1234",
        "username": "<MAC address of my Pi>",
        "port": 51585,
        "pin": "123-45-678",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        }
    ]
}
```

### Homebridge UI Version

4.45.0

### Homebridge Version

1.4.1

### Node.js Version

16.15.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 1 B

**Comment by oznu** [comment]
This should sort it:

```
sudo apt update
sudo apt install homebridge
```
