### ISSUE TITLE
Logs on Status Page - broken Chrome 104

### ISSUE THREAD

**Issue by devenbj** [oznu/homebridge-config-ui-x#1400]
### Describe The Bug

The Homebridge Logs on the Status page remains blank, even though the Logs menu item takes me to a fully visible logs page. :) This is not an issue on the latest version of Safari on Mac, nor on Firefox Ubuntu. It is an issue on Chrome 104 on Ubuntu and Mac. It was not present on Chrome 103 on Windows 11, nor Edge 103 on Windows 11. 

I have restarted the server, homebridge, cleared browser cache and restarted browsers, reset to default layout, manually removed and added logs widget. No impact.

The logs are browser errors that are showing up.

Please let me know if there is any other logging or troubleshooting to assist.

### Logs

```text
main.2129f16d21c6e853.js:1 ERROR Error: This API only accepts integers
    at main.2129f16d21c6e853.js:1:1881023
    at Array.forEach (<anonymous>)
    at f._verifyIntegers (main.2129f16d21c6e853.js:1:1880968)
    at f.resize (main.2129f16d21c6e853.js:1:1878155)
    at s.fit (main.2129f16d21c6e853.js:1:1775772)
    at main.2129f16d21c6e853.js:1:169420
    at Ee.<computed> (polyfills.72f9dfbbeffa1ed2.js:1:29353)
    at X.invokeTask (polyfills.72f9dfbbeffa1ed2.js:1:7865)
    at Object.onInvokeTask (main.2129f16d21c6e853.js:1:2257303)
    at X.invokeTask (polyfills.72f9dfbbeffa1ed2.js:1:7786)
handleError @ main.2129f16d21c6e853.js:1
main.2129f16d21c6e853.js:1 ERROR Error: This API only accepts integers
    at main.2129f16d21c6e853.js:1:1881023
    at Array.forEach (<anonymous>)
    at f._verifyIntegers (main.2129f16d21c6e853.js:1:1880968)
    at f.resize (main.2129f16d21c6e853.js:1:1878155)
    at s.fit (main.2129f16d21c6e853.js:1:1775772)
    at Object.next (main.2129f16d21c6e853.js:1:169949)
    at A.next (main.2129f16d21c6e853.js:1:1690948)
    at R._next (main.2129f16d21c6e853.js:1:1690632)
    at R.next (main.2129f16d21c6e853.js:1:1690327)
    at h (main.2129f16d21c6e853.js:1:1701116)
```

### Homebridge UI Version

4.50.0

### Homebridge Version

1.5.0

### Node.js Version

16.16.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

**Comment by longzheng** [comment]
I traced the issue down to `this._charSizeService.measure()`

On Chrome 104, `this._measureElement.getBoundingClientRect();` is returning all `0`s

<img width="993" alt="image" src="https://user-images.githubusercontent.com/484912/183228816-9e1bf963-1cec-437e-bfa5-94a22ddd52cc.png">

On Firefox, it returns valid values

<img width="740" alt="image" src="https://user-images.githubusercontent.com/484912/183228831-5b7d8fa3-65c8-4572-9c99-a0ec7ddcd510.png">

**Comment by OwlBawl** [comment]
The same issue here here after last Chrome update

**Comment by oznu** [comment]
There is a fix for this in test.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by bo-2221** [comment]
homebridge-config-ui-x v4.50.1-test.5 is working, the log shows something again

**Comment by OwlBawl** [comment]
Confirm working now
