### ISSUE TITLE
Logs and terminal widget shows nothing, regular terminal page works fine

### ISSUE THREAD

**Issue by Cyberbeni** [oznu/homebridge-config-ui-x#1402]
### Describe The Bug

I installed the official Homebridge Raspberry Pi image like a year ago, it has the hb-service CLI but never used that. It was working before with the same Homebridge/UI versions, Node was 16.13.0 I think.

I was trying to install Node-RED with the recommended command: https://nodered.org/docs/getting-started/raspberrypi

But that just deleted node/npm from /usr/local/bin, had to use hb-config through ssh to reinstall it.

Then I just installed Node-RED directly from npm, set it up with the Zigbee2MQTT plugin, it's working fine.

I might have did some other stuff too, don't remember.

Then later I noticed that the logs are empty in the UI. I also tried the terminal widget and that was also empty, giving the same error in the console. The regular terminal tab works fine. I can also read the log file and it shows recent logs.

![empty logs](https://user-images.githubusercontent.com/8356175/183292510-55c91836-85eb-4a82-9df9-ee8583d95d17.PNG)

### Logs

```text
Developer tools shows the following 2 errors when I refresh the status page with the logs widget on it:


main.2129f16d21c6e853.js:1 
        
       ERROR Error: This API only accepts integers
    at main.2129f16d21c6e853.js:1:1881023
    at Array.forEach (<anonymous>)
    at f._verifyIntegers (main.2129f16d21c6e853.js:1:1880968)
    at f.resize (main.2129f16d21c6e853.js:1:1878155)
    at s.fit (main.2129f16d21c6e853.js:1:1775772)
    at main.2129f16d21c6e853.js:1:169420
    at Ee.<computed> (polyfills.72f9dfbbeffa1ed2.js:1:29353)
    at X.invokeTask (polyfills.72f9dfbbeffa1ed2.js:1:7865)
    at Object.onInvokeTask (main.2129f16d21c6e853.js:1:2257303)
    at X.invokeTask (polyfills.72f9dfbbeffa1ed2.js:1:7786)
    
main.2129f16d21c6e853.js:1 
        
       ERROR Error: This API only accepts integers
    at main.2129f16d21c6e853.js:1:1881023
    at Array.forEach (<anonymous>)
    at f._verifyIntegers (main.2129f16d21c6e853.js:1:1880968)
    at f.resize (main.2129f16d21c6e853.js:1:1878155)
    at s.fit (main.2129f16d21c6e853.js:1:1775772)
    at Object.next (main.2129f16d21c6e853.js:1:169949)
    at A.next (main.2129f16d21c6e853.js:1:1690948)
    at R._next (main.2129f16d21c6e853.js:1:1690632)
    at R.next (main.2129f16d21c6e853.js:1:1690327)
    at h (main.2129f16d21c6e853.js:1:1701116)
```
```


### Config

_No response_

### Homebridge UI Version

4.50.0

### Homebridge Version

1.5.0

### Node.js Version

16.16.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/issues/1400
