### ISSUE TITLE
Homebridge won't start - Plugin /usr/local/lib/node_modules/homebridge-config-ui-x does not contain a package.json

### ISSUE THREAD

**Issue by bjornand1** [oznu/homebridge-config-ui-x#1471]
### Current Situation

After having problems updating a package, I used terminal to uninstall and reinstall the UI plugin with sudo. After this, Homebridge won't restart and I suspect this error is (at least part of) the problem:

Plugin /usr/local/lib/node_modules/homebridge-config-ui-x does not contain a package.json

I see that there is no folder for this plugin, but the UI works.

### Logs

```text
I also get this error, in addition to some about Node version:
[3/15/2023, 11:56:06 AM] Error: Request failed with status code 404
    at createError (/volume1/@appdata/homebridge/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/volume1/@appdata/homebridge/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/volume1/@appdata/homebridge/lib/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[3/15/2023, 11:56:06 AM] Got SIGTERM, shutting down Homebridge...
[3/15/2023, 11:56:06 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/volume1/@appdata/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/volume1/@appdata/homebridge/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/volume1/@appdata/homebridge/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:527:28)
    at process.emit (/volume1/@appdata/homebridge/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

### Homebridge UI Version

homebridge-config-ui-x v4.50.2

### Homebridge Version

1.6.0

### Node.js Version

16.16.0

### Operating System

Synology DSM

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by bjornand1** [comment]
I am starting to suspect that there is some discrepancy between locations. Before doing the uninstall/reinstall of the UI package, everything Homebridge-related was located in:

var/packages/homebridge/shares/homebridge

Most of it is still there, but the error message about missing package.json files refer to:

var/usr/local/lib

There are two folders there, homebridge-config-ui-x and homebridge-synology, which is the plugin that could not be updated and triggered all this.

Being very unfamiliar with terminal work, I fear installing plugins using npm commands in the terminal puts things in the wrong place?

**Comment by bjornand1** [comment]
Further update, it seems it might be the Verisure plugin that is the culprit - disabled it and Homebridge starts up fine.
