### ISSUE TITLE
Crashes half way through upgrade

### ISSUE THREAD

**Issue by jamie-2bit** [oznu/homebridge-config-ui-x#1475]
### Describe The Bug

Upgrading via the homebridge plugin page from 4.45.0 to the latest version causes the install to hang near the halfway point. See below:

USER: root
DIR: /usr/local
CMD: npm install -g homebridge-config-ui-x@latest

npm ERR! process terminated
npm ERR! signal SIGTERM

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-29T09_15_57_364Z-debug-0.log

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Command failed. Please review log for details.

### Logs

```text
1392 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/string_decoder/node_modules/safe-buff>
1393 silly placeDep node_modules/homebridge-config-ui-x/node_modules/string-width ansi-regex@2.1.1 OK for: s>
1394 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/string-width/node_modules/strip-ansi >
1395 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/string-width/node_modules/ansi-regex >
1396 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/tar-fs/node_modules/chownr Completed >
1397 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/tar-stream/node_modules/readable-stre>
1398 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/tcp-port-used/node_modules/debug Comp>
1399 silly placeDep node_modules/homebridge-config-ui-x/node_modules/unzipper safe-buffer@5.1.2 OK for: read>
1400 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/unzipper/node_modules/readable-stream>
1401 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/unzipper/node_modules/safe-buffer Com>
1402 timing idealTree:node_modules/homebridge-config-ui-x/node_modules/send/node_modules/debug/node_modules/>
1403 timing idealTree:buildDeps Completed in 41112ms
1404 timing idealTree:fixDepFlags Completed in 18ms
1405 timing idealTree Completed in 42865ms
1406 timing reify:loadTrees Completed in 43797ms
1407 timing reify:diffTrees Completed in 63ms
1408 silly reify mark retired [
1408 silly reify   '/usr/local/lib/node_modules/homebridge-config-ui-x',
1408 silly reify   '/usr/local/bin/homebridge-config-ui-x',
1408 silly reify   '/usr/local/bin/hb-service'
1408 silly reify ]
1409 silly reify moves {
1409 silly reify   '/usr/local/lib/node_modules/homebridge-config-ui-x': '/usr/local/lib/node_modules/.homeb>
1409 silly reify   '/usr/local/bin/homebridge-config-ui-x': '/usr/local/bin/.homebridge-config-ui-x-t7FQLPa6>
1409 silly reify   '/usr/local/bin/hb-service': '/usr/local/bin/.hb-service-cTvJcb2G'
1409 silly reify }
1410 timing reify:retireShallow Completed in 403855ms
1411 timing reify:rollback:retireShallow Completed in 3ms
1412 timing command:install Completed in 447802ms
1413 verbose stack Error: process terminated
1413 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.j>
1413 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist>
1413 verbose stack     at process.emit (node:events:539:35)
1414 verbose cwd /usr/local
1415 verbose Linux 5.10.63-v8+
1416 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-config-ui-x@latest"
1417 verbose node v16.15.0
1418 verbose npm  v8.5.5
1419 error process terminated
1420 error signal SIGTERM
1421 verbose exit 1
1422 timing npm Completed in 448793ms
1423 verbose unfinished npm timer reify 1680081358346
1424 verbose code 1
1425 error A complete log of this run can be found in:
1425 error     /root/.npm/_logs/2023-03-29T09_15_57_364Z-debug-0.log
```

### Homebridge UI Version

homebridge-config-ui-x v4.45.0

### Homebridge Version

v1.5.0

### Node.js Version

v16.15.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by stephenjmcmahon** [comment]
I have also received this issue. I also have the same hardware and utilize it via Docker.

`2050 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/find-my-way Completed in 39158ms
2051 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/text-decoding Completed in 39322ms
2052 http fetch GET 200 https://registry.npmjs.org/@fastify/static/-/static-6.5.0.tgz 38611ms (cache miss)
2053 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/@fastify/static Completed in 40303ms
2054 http fetch GET 200 https://registry.npmjs.org/pino/-/pino-8.11.0.tgz 36244ms (cache miss)
2055 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/pino Completed in 41140ms
2056 http fetch GET 200 https://registry.npmjs.org/@nestjs/swagger/-/swagger-6.0.5.tgz 39869ms (cache miss)
2057 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/@nestjs/swagger Completed in 42050ms
2058 http fetch GET 200 https://registry.npmjs.org/validator/-/validator-13.9.0.tgz 39900ms (cache miss)
2059 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/validator Completed in 42083ms
2060 http fetch GET 200 https://registry.npmjs.org/luxon/-/luxon-1.28.1.tgz 42109ms (cache miss)
2061 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/luxon Completed in 43105ms
2062 http fetch GET 200 https://registry.npmjs.org/@nestjs/core/-/core-9.0.8.tgz 41233ms (cache miss)
2063 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/@nestjs/core Completed in 43594ms
2064 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/class-transformer Completed in 44389ms
2065 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/@types/node Completed in 44817ms
2066 http fetch GET 200 https://registry.npmjs.org/fastify/-/fastify-4.3.0.tgz 37103ms (cache miss)
2067 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/fastify Completed in 45259ms
2068 http fetch GET 200 https://registry.npmjs.org/@nestjs/common/-/common-9.0.8.tgz 43080ms (cache miss)
2069 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/@nestjs/common Completed in 45411ms
2070 http fetch GET 200 https://registry.npmjs.org/@fastify/swagger/-/swagger-7.4.1.tgz 43805ms (cache miss)
2071 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/@fastify/swagger Completed in 45471ms
2072 http fetch GET 200 https://registry.npmjs.org/@babel/runtime-corejs3/-/runtime-corejs3-7.21.0.tgz 45799ms (cache miss)
2073 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/@babel/runtime-corejs3 Completed in 48231ms
2074 http fetch GET 200 https://registry.npmjs.org/dayjs/-/dayjs-1.11.4.tgz 39439ms (cache miss)
2075 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/dayjs Completed in 48517ms
2076 http fetch GET 200 https://registry.npmjs.org/swagger-ui-dist/-/swagger-ui-dist-4.13.2.tgz 47215ms (cache miss)
2077 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/swagger-ui-dist Completed in 48703ms
2078 http fetch GET 200 https://registry.npmjs.org/ajv/-/ajv-8.12.0.tgz 38736ms (cache miss)
2079 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/ajv Completed in 48935ms
2080 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch Completed in 49234ms
2081 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/lodash Completed in 52199ms
2082 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/class-validator Completed in 52822ms
2083 http fetch GET 200 https://registry.npmjs.org/libphonenumber-js/-/libphonenumber-js-1.10.24.tgz 46676ms (cache miss)
2084 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/libphonenumber-js Completed in 53321ms
2085 http fetch GET 200 https://registry.npmjs.org/homebridge-config-ui-x/-/homebridge-config-ui-x-4.50.2.tgz 56146ms (cache miss)
2086 timing reifyNode:node_modules/homebridge-config-ui-x Completed in 56849ms
2087 http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-7.5.6.tgz 56671ms (cache miss)
2088 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/rxjs Completed in 61046ms
2089 http fetch GET 200 https://registry.npmjs.org/core-js-pure/-/core-js-pure-3.29.1.tgz 53291ms (cache miss)
2090 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/core-js-pure Completed in 62360ms
2091 timing reify:unpack Completed in 62472ms
2092 timing reify:rollback:createSparse Completed in 9884ms
2093 timing reify:rollback:retireShallow Completed in 20ms
2094 timing command:install Completed in 315125ms
2095 verbose stack Error: process terminated
2095 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:198:39
2095 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
2095 verbose stack     at process.emit (node:events:539:35)
2096 verbose cwd /usr/local
2097 verbose Linux 5.10.103-v7+
2098 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-config-ui-x@latest"
2099 verbose node v16.15.0
2100 verbose npm  v8.5.5
2101 error process terminated
2102 error signal SIGTERM
2103 verbose exit 1
2104 timing npm Completed in 316403ms
2105 verbose unfinished npm timer reify 1680311327746
2106 verbose code 1
2107 error A complete log of this run can be found in:
2107 error     /root/.npm/_logs/2023-04-01T01_08_46_546Z-debug-0.log`

**Comment by stephenjmcmahon** [comment]
commenting to prevent "stale" state

**Comment by donavanbecker** [comment]
Can you try the latest test version?
