### ISSUE TITLE
Websocket error crashing homebridge

### ISSUE THREAD

**Issue by onefish2** [oznu/homebridge-config-ui-x#15]
I am getting this error for the past few updates. Its also crashing homebridge. Current version is 2.2.2

/usr/lib/node_modules/homebridge-config-ui-x/node_modules/ws/lib/websocket.js:371
      const err = new Error(
                  ^
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/ws/lib/websocket.js:371:19)
    at LogsWssHandler.send (/usr/lib/node_modules/homebridge-config-ui-x/src/wss/logs.ts:43:13)
    at emitOne (events.js:116:13)
    at PipeSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at PipeSocket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

This is the Configuration UI plugin for Homebridge section of the config.json 
{
            "platform": "config",
            "name": "Config",
            "port": 8766,
            "restart": "sudo systemctl restart homebridge",
            "log": "systemd",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true
},

I have followed all of your instructions for setting up this plugin with systemd and sudo mode.

**Comment by oznu** [comment]
Thanks for raising this. I see the problem and I'll push up a fix soon.

**Comment by oznu** [comment]
@onefish2 - that bug should be fixed in 2.2.3. If symptoms persist feel free to re-open this issue.
