### ISSUE TITLE
Latest version 4.52.0 wont update

### ISSUE THREAD

**Issue by mikellas1983** [oznu/homebridge-config-ui-x#1624]
### Describe The Bug

Trying to update to the latest version

### Logs

```text
C:\WINDOWS\system32>npm install -g homebridge-config-ui-x@latest
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\lodash'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\lodash'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\validator\es'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\validator\\es'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\rxjs',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\rxjs'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\rxjs'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@fastify\static\test\static\deep\path\for'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify\\static\\test\\static\\deep\\path\\for'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@oznu',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@oznu'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@oznu'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify\\static',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@fastify\static'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify\\static'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@homebridge\node-pty-prebuilt-multiarch
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/check-prebuild.js || prebuild-install --verbose || node scripts/install.js
npm ERR! prebuild-file-path: C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@homebridge\node-pty-prebuilt-multiarch\prebuilds\win32-x64\node.abi108.node
npm ERR! Prebuild binary missing for platform.
npm ERR! prebuild-install info begin Prebuild-install version 7.1.1
npm ERR! prebuild-install info looking for local prebuild @ prebuilds\node-pty-prebuilt-multiarch-v0.11.8-node-v108-win32-x64.tar.gz
npm ERR! prebuild-install info looking for cached prebuild @ C:\Users\Nicolas Server\AppData\Local\npm-cache\_prebuilds\d0ef09-node-pty-prebuilt-multiarch-v0.11.8-node-v108-win32-x64.tar.gz
npm ERR! prebuild-install http request GET https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v0.11.8/node-pty-prebuilt-multiarch-v0.11.8-node-v108-win32-x64.tar.gz
npm ERR! prebuild-install http 404 https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v0.11.8/node-pty-prebuilt-multiarch-v0.11.8-node-v108-win32-x64.tar.gz
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.18.0 runtime=node arch=x64 libc= platform=win32)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "C:\Python39\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.0/node-v18.18.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.18.0/node-v18.18.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.18.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.18.0/win-x64/node.lib
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:401:16
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nicolas Server\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@homebridge\node-pty-prebuilt-multiarch
npm ERR! gyp ERR! node -v v18.18.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\Nicolas Server\AppData\Local\npm-cache\_logs\2023-11-04T16_49_07_408Z-debug-0.log
```

### Homebridge UI Version

4.51.2

### Homebridge Version

1.7.0

### Node.js Version

18.18.0

### Operating System

Windows 11

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
@mikellas1983, have you tried updating again?

**Comment by donavanbecker** [comment]
Are you having the same issues with 4.52.1?

**Comment by mikellas1983** [comment]
Hi , 

Latest version went through just fine Thanks!!
