### ISSUE TITLE
Homebridge crashes with 3.9.0

### ISSUE THREAD

**Issue by niccolospa** [oznu/homebridge-config-ui-x#172]
I'm getting this error after the last update:
Error: Cannot find module './clone.js'
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Function.Module._resolveFilename (module.js:538:15)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Function.Module._load (module.js:468:25)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Module.require (module.js:587:17)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at require (internal/module.js:11:18)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/graceful-fs/graceful-fs.js:4:13
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Module._compile (module.js:643:30)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Object.Module._extensions..js (module.js:654:10)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Module.load (module.js:556:32)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at tryModuleLoad (module.js:499:12)
Nov 03 00:04:05 inkyraspberrypi homebridge[25415]:     at Function.Module._load (module.js:491:3)

Do anyone has the same problem?

**Comment by niccolospa** [comment]
After reinstalling the plugin, homebridge turns back to work!
