### ISSUE TITLE
after update

### ISSUE THREAD

**Issue by entoryFB** [oznu/homebridge-config-ui-x#1748]
### Describe The Bug

[19/11/2023, 11:28:03] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'find')
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:256:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:206:7)

### Logs

```text
[19/11/2023, 11:25:03] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'find')
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:256:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:206:7)
[19/11/2023, 11:26:03] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'find')
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:256:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:206:7)
[19/11/2023, 11:27:03] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'find')
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:256:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:206:7)
```

### Homebridge UI Version

homebridge-config-ui-x v4.52.3

### Homebridge Version

1.7.0

### Node.js Version

18.18.2

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by bwp91** [comment]
Hi @entoryFB, since this is an issue specific to a homebridge plugin, you would need to seek advice from the plugin maintainer.

Please search on the plugin's github repo and if necessary create an issue there.

- https://github.com/kopiro/homebridge-tapo-camera

---

Out of interest, is this sending homebridge into a constant restart loop?

**Comment by entoryFB** [comment]
Thank you very much for the information. I asked the question with the plugin Team
The homebridge runs perfectly. The error message only comes every two minutes

**Comment by entoryFB** [comment]
Thanks
