### ISSUE TITLE
Homebridge keeps restarting after update to homebridge-config-ui-x v4.53.0

### ISSUE THREAD

**Issue by jaydkay** [oznu/homebridge-config-ui-x#1826]
### Describe The Bug

Just updated from homebridge-config-ui-x v4.52.3 to homebridge-config-ui-x v4.53.0. After selecting "Restart", Homebridge doesn't come up again, it just keeps on crashing and restarting showing the lines below in the log. I tried reverting to homebridge-config-ui-x v4.52.3, but the problem persists. I did not changes to Homebridge itself.

### Logs

```text
[25.11.2023, 11:12:30] [Homebridge UI] Running Command: sudo -E -n npm run upgrade-install -- 4.53.0 /usr
[25.11.2023, 11:13:52] [Homebridge UI] Homebridge restart request received
[25.11.2023, 11:13:52] [Homebridge UI] Sending SIGTERM to process...
[25.11.2023, 11:13:52] [HB Supervisor] Stopping services...
[25.11.2023, 11:13:52] Got SIGTERM, shutting down Homebridge...
[25.11.2023, 11:13:57] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[25.11.2023, 11:14:06] [HB Supervisor] OS: Linux 5.10.103-v7+ arm
[25.11.2023, 11:14:06] [HB Supervisor] Node.js v18.18.2 /usr/bin/node
[25.11.2023, 11:14:06] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[25.11.2023, 11:14:06] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[25.11.2023, 11:14:14] [Homebridge UI] Homebridge UI v4.53.0 is listening on :: port 8581
[25.11.2023, 11:14:15] [HB Supervisor] Starting Homebridge with extra flags: -I
[25.11.2023, 11:14:15] [HB Supervisor] Started Homebridge v1.7.0 with PID: 9154
[25.11.2023, 11:14:17] Loaded config.json with 2 accessories and 3 platforms.
[25.11.2023, 11:14:17] Loaded 3 cached accessories from cachedAccessories.
[25.11.2023, 11:14:17] TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at Accessory._sideloadServices (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1800:13)
    at Function.Accessory.deserialize (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2188:15)
    at Function.deserialize (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:172:33)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:240:34
    at Array.map (<anonymous>)
    at BridgeService.loadCachedPlatformAccessoriesFromDisk (/usr/lib/node_modules/homebridge/src/bridgeService.ts:239:58)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:170:5)
[25.11.2023, 11:14:17] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:517:28)
    at process.emit (/usr/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[25.11.2023, 11:14:17] Got SIGTERM, shutting down Homebridge...
[25.11.2023, 11:14:22] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[25.11.2023, 11:14:27] [HB Supervisor] Restarting Homebridge...
[25.11.2023, 11:14:27] [HB Supervisor] Starting Homebridge with extra flags: -I
[25.11.2023, 11:14:27] [HB Supervisor] Started Homebridge v1.7.0 with PID: 9281
[25.11.2023, 11:14:29] Loaded config.json with 2 accessories and 3 platforms.
[25.11.2023, 11:14:30] Loaded 3 cached accessories from cachedAccessories.
[25.11.2023, 11:14:30] TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at Accessory._sideloadServices (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1800:13)
    at Function.Accessory.deserialize (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2188:15)
    at Function.deserialize (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:172:33)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:240:34
    at Array.map (<anonymous>)
    at BridgeService.loadCachedPlatformAccessoriesFromDisk (/usr/lib/node_modules/homebridge/src/bridgeService.ts:239:58)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:170:5)
[25.11.2023, 11:14:30] Got SIGTERM, shutting down Homebridge...
[25.11.2023, 11:14:30] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:517:28)
    at process.emit (/usr/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[25.11.2023, 11:14:35] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[25.11.2023, 11:14:40] [HB Supervisor] Restarting Homebridge...
```

### Homebridge UI Version

4.53.0

### Homebridge Version

1.7.0

### Node.js Version

18.18.2

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by jaydkay** [comment]
I'm just answering myself here: After I removed the file `/var/lib/homebridge/accessories/cachedAccessories` everything is working fine again. I don't know if the file was corrupted and - if it was - why this happened at the same time when I updated the UI, but at least for me the problem is solved.
