### ISSUE TITLE
Cannot start homebridge after updating to config-ui-x 4.55.0

### ISSUE THREAD

**Issue by DaphneINOPIA** [oznu/homebridge-config-ui-x#1975]
### Current Situation

After updating to the latest ui version I started getting an error in my logs, which prevents homebridge from starting (it goes into a restarting loop)

I tried rolling back to previous versions but without success.

### Logs

```
[07/01/2024, 14:41:06] [HB Supervisor] OS: Linux 6.1.21+ arm
[07/01/2024, 14:41:06] [HB Supervisor] Node.js v20.10.0 /usr/local/bin/node
[07/01/2024, 14:41:06] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[07/01/2024, 14:41:06] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[07/01/2024, 14:41:42] [Homebridge UI] Homebridge UI v4.55.0 is listening on :: port 8581
[07/01/2024, 14:41:46] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at equalTxt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/utils/equal-txt.ts:2:24)
    at Browser.updateService (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:145:21)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:108:30
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:106:25
    at Array.forEach (<anonymous>)
    at EventEmitter.onresponse (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:98:34)
    at EventEmitter.emit (node:events:514:28)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8)
```

### Homebridge UI Version

4.55.0

### Homebridge Version

1.7.0

### Node.js Version

20.10.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi Zero W

**Comment by donavanbecker** [comment]
Duplicate to #1973, workaround currently is to turn off insecure mode in Homebridge settings until a fix is released.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-config-ui-x@beta/>=4.55.1-beta.2/orange)](https://www.npmjs.com/package/homebridge-config-ui-x)

[Click here to find out how to install Beta](https://github.com/homebridge/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes)

**Comment by donavanbecker** [comment]
4.55.1 has been released with a fix for this.

**Comment by donavanbecker** [comment]
There was a fix that was implemented to the `bonjour-service` package. So we have reverted the quick fix to allow for the newer version of `bonjour-service`, so now we have a new beta.

Can someone try the latest beta and confirm that this fix resolves the issues we were having: 

[![npm version](https://badgen.net/badge/homebridge-config-ui-x@beta/>=4.55.2-beta.2/orange)](https://www.npmjs.com/package/homebridge-config-ui-x)

[Click here to find out how to install Beta Versions](https://github.com/homebridge/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes)

**Comment by kalety** [comment]
I've installed the beta version, all stable for now...

**Comment by donavanbecker** [comment]
Thanks! Going to close this comment as we will release this in the next version.
