### ISSUE TITLE
Cannot Login to UI-X

### ISSUE THREAD

**Issue by dawger1** [oznu/homebridge-config-ui-x#20]
Hi there,

I've installed homebridge-config-ui-x, and am able to get to the login page localhost:8080.  When I enter the default username and password "admin" (without quotes), I get "Invalid Username and Password".

Here are my config.json details:
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true,
            "log": "/home/pi/homebridge/config/logs/homebridge.log",
            "theme": "blue",
            "restart": "/home/pi/homebridge/ docker-compose restart homebridge"
        }

Has anybody else seen this?  What have I done wrong?  

I don't think it's related, but I updated sudoers using visudo as instructed, adding homebridge    ALL=(ALL) NOPASSWD: ALL at the end (although I'm not exactly sure what my username is.  Is this the username I use when I SSH from Putty / Filezilla?

**Comment by oznu** [comment]
Hi @dawger1,

Can you confirm if a new file called `auth.json` has been created in the same directory as your `config.json`?

If you could also you also provide the homebridge log output from a restart of Homebridge I'll see what's going on here.

**Comment by dawger1** [comment]
Hi @oznu,

Thanks for the quick response!  Yes, there is a file called auth.json in the same folder as config.json.  The username is admin, and the password is hashed.

Here's a copy of the homebridge log:
`/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:42
    var error = dns_sd.buildException(errorCode);
                       ^
Error: dns service error: unknown
    at Advertisement.on_service_registered (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/mdns_service.js:18:40)
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-1-28 01:03:15] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/homebridge/node_modules/homebridge-config-ui-x'.
[2018-1-28 01:03:17] Loaded plugin: homebridge-config-ui-x
[2018-1-28 01:03:17] Registering platform 'homebridge-config-ui-x.config'
[2018-1-28 01:03:17] ---
[2018-1-28 01:03:17] Loaded plugin: homebridge-dummy
[2018-1-28 01:03:17] Registering accessory 'homebridge-dummy.DummySwitch'
[2018-1-28 01:03:17] ---
[2018-1-28 01:03:17] Loaded plugin: homebridge-liftmaster2
[2018-1-28 01:03:17] Registering platform 'homebridge-liftmaster2.LiftMaster2'
[2018-1-28 01:03:17] ---
[2018-1-28 01:03:19] Loaded plugin: homebridge-nest
[2018-1-28 01:03:19] Registering platform 'homebridge-nest.Nest'
[2018-1-28 01:03:19] ---
[2018-1-28 01:03:20] Loaded plugin: homebridge-platform-wemo
[2018-1-28 01:03:20] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2018-1-28 01:03:20] ---
[2018-1-28 01:03:20] Loaded config.json with 0 accessories and 4 platforms.
[2018-1-28 01:03:20] ---
[2018-1-28 01:03:20] Loading 4 platforms...
[2018-1-28 01:03:20] [WeMo Platform] Initializing BelkinWeMo platform...
[2018-1-28 01:03:20] [MyQ] Initializing LiftMaster2 platform...
[2018-1-28 01:03:20] [Nest] Initializing Nest platform...
[2018-1-28 01:03:20] [Nest] Fetching Nest devices.
[2018-1-28 01:03:20] [Config] Initializing config platform...
[2018-1-28 01:03:20] Loading 0 accessories...
[2018-1-28 01:03:21] [WeMo Platform] Online: Front Room Lights [149182CCA07C]
[2018-1-28 01:03:26] [Config] Using Form Authentication
[2018-1-28 01:03:26] [Config] Console is listening on port 8080.
[2018-1-28 01:03:26] [WeMo Platform] Online: Playroom Lamp [6038E05BB254]
[2018-1-28 01:03:26] [WeMo Platform] Online: Living Room Lights [6038E0496D48]
[2018-1-28 01:03:26] [WeMo Platform] Online: Davids Lamp [6038E05BA710]
[2018-1-28 01:03:26] [WeMo Platform] Online: Upstairs Christmas Lights [58EF68D9EE70]
[2018-1-28 01:03:26] [WeMo Platform] Online: Master Bathroom [149182CCB18C]
[2018-1-28 01:03:26] [WeMo Platform] Online: Front Porch and Garage Lights [149182505F6C]
[2018-1-28 01:03:26] [WeMo Platform] Online: Kitchen Table Lights [149182D8C390]
[2018-1-28 01:03:26] [WeMo Platform] Online: Kitchen Lights [6038E04B2A04]
[2018-1-28 01:03:26] [WeMo Platform] Online: Front Room Christmas Lights [58EF68D9FCC8]
[2018-1-28 01:03:26] [WeMo Platform] Online: Master Bathroom Lights [149182D86786]
[2018-1-28 01:03:26] [WeMo Platform] Online: Main Floor Bathroom Lights [149182D88550]
[2018-1-28 01:03:26] [WeMo Platform] Online: Dining Room Lights [149182D865E4]
[2018-1-28 01:03:27] [WeMo Platform] Front Porch and Garage Lights - Get state: On
[2018-1-28 01:03:27] [WeMo Platform] Kitchen Table Lights - Get state: On
[2018-1-28 01:03:27] [WeMo Platform] Kitchen Lights - Get state: On
[2018-1-28 01:03:28] [MyQ] Initializing platform accessory 'Garage Door Opener (ID: 60144482)'...
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[2018-1-28 01:03:29] [Nest] Initializing platform accessory 'Entryway Thermostat'...
Setup Payload:
X-HM://0023ISYWY9634
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
[Deleted for brevity]
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2018-1-28 01:03:29] Homebridge is running on port 51826.
`

**Comment by oznu** [comment]
The code is suppose to transform auth.json files from the original conifg-ui plugin, so if you changed the password for the admin user when using that plugin it will be transfered to config-ui-x.

Otherwise try deleting the auth.json and restarting homebridge, this will cause the admin user to be recreated.

It looks like you are using Docker, are you using my oznu/homebridge image or another?

**Comment by oznu** [comment]
Hi @dawger1,

Since you're using my [oznu/homebridge](https://github.com/oznu/docker-homebridge) you can setup homebridge-ui-config-x just by starting your container with the `HOMEBRIDGE_CONFIG_UI=1` flag:

```shell
docker run \
  --net=host \
  --name=homebridge \
  -e PUID=<UID> -e PGID=<GID> \
  -e TZ=<timezone> \
  -e HOMEBRIDGE_CONFIG_UI=1
  -e HOMEBRIDGE_CONFIG_UI_PORT=8080
  -e HOMEBRIDGE_CONFIG_UI_THEME=blue
  -v </path/to/config>:/homebridge \
  oznu/homebridge
```

or if you're using docker-compose:

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    environment:
      - TZ=Australia/Sydney
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - HOMEBRIDGE_CONFIG_UI_THEME=blue
    volumes:
      - ./volumes/homebridge:/homebridge
```

**Remove the homebridge-config-ui-x config block from your `config.json` and delete the `node_modules` folder from your `/homebridge` directory before doing this.**

**Comment by dawger1** [comment]
I followed your instructions, restarted homebridge and ran docker-compose logs -f, and now I get this:

> docker-compose logs -f
Attaching to homebridge_homebridge_1
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_1  | standard_init_linux.go:195: exec user process caused "exec format error"
homebridge_homebridge_1 exited with code 1

Not sure what I've done wrong, but it looks like I've torched my server now.  All of my accessories are now showing no response.  Is there a way to fix this without starting over from scratch? (BTW: thank you again for the help.  I realize that we're some way off where we started with my original request).

**Comment by oznu** [comment]
You must be running on a Raspberry Pi 😄 

Please replace `oznu/homebridge:latest` with `oznu/homebridge:raspberry-pi` and run `docker-compose pull homebridge` again.

**Comment by dawger1** [comment]
Whoops, sorry!  Should've pointed that out right up front.  I just pulled the raspberry-pi distribution, and all is well again!  I had some issues with the plugin, but it's so much easier to install the plugins and modify config.json through the portal (especially if you accidentally end up in a boot loop like I did).  Excellent work, and thank you very much for all of your help again!

**Comment by oznu** [comment]
Glad to see you got it working!
