### ISSUE TITLE
Cannot install package because of node-gyp-build error

### ISSUE THREAD

**Issue by mrks1337** [oznu/homebridge-config-ui-x#2030]
### Describe The Bug

Hello!
I am running Homebridge on my Loxberry and wanted to give this plugin a try: https://github.com/rudyberends/homebridge-loxone-proxy
During npm installation I get the following error:

```
USER: loxberry
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-loxone-proxy@1.9.1

(##################) ⠦ reify:rxjs: timing reifyNode:node_modules/homebridge-loxone-pro
> bufferutil@4.0.8 install
> node-gyp-build

(##################) ⠏ reify:rxjs: timing reifyNode:node_modules/homebridge-loxone-pro
make: Entering directory '/usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.nodeodules/homebridge-loxone-pro
make: g++: No such file or directory
make: *** [bufferutil.target.mk:137: Release/obj.target/bufferutil.node] Error 127
make: Leaving directory '/usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Linux 6.1.21-v8+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil
gyp ERR! node -v v18.19.1
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in: /opt/loxberry/.npm/_logs/2024-03-28T14_27_08_369Z-debug-0.log

Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
```

These errors are happening for v1.9.1 and v1.10.0-beta-5.

### Logs

[homebridge-loxone-proxy-error.log](https://github.com/homebridge/homebridge-config-ui-x/files/14814967/homebridge-loxone-proxy-error.log)

### Homebridge UI Version

Latest

### Homebridge Version

Latest

### Node.js Version

20.12.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by mrks1337** [comment]
I just update to latest Node LTS (20.12.0) but I receive the same error:

```
USER: loxberry
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-loxone-proxy@1.9.1

(##################) ⠸ reify:rxjs: timing reifyNode:node_modules/homebridge-loxone-pro
> bufferutil@4.0.8 install
> node-gyp-build

(##################) ⠦ reify:rxjs: timing reifyNode:node_modules/homebridge-loxone-pro
make: Entering directory '/usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.nodeodules/homebridge-loxone-pro
make: g++: No such file or directory
make: *** [bufferutil.target.mk:132: Release/obj.target/bufferutil.node] Error 127
make: Leaving directory '/usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Linux 6.1.21-v8+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil
gyp ERR! node -v v20.12.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-loxone-proxy/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in: /opt/loxberry/.npm/_logs/2024-03-28T14_37_36_162Z-debug-0.log

Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

```

**Comment by bwp91** [comment]
In the homebridge terminal, run this:

```
sudo apt install build-essential
```

and then try to install the plugin again

**Comment by bwp91** [comment]
Gonna close this as issues for specific plugins should really be opened against the plugin repo on GitHub, not on this UI repo.

Hopefully the command I suggested above worked for you 👍

**Comment by mrks1337** [comment]
Hi @bwp91
thank you for your package suggestion, this fixed the problem! 🎉
