### ISSUE TITLE
CLI: "SyntaxError: Unexpected token '?'"

### ISSUE THREAD

**Issue by shanemcw** [oznu/homebridge-config-ui-x#2179]
### Describe The Bug

On running "homebridge -h" CLI fails and stderr reports

```
/usr/local/lib/node_modules/homebridge/node_modules/commander/lib/command.js:396
    enableOrNameAndArgs = enableOrNameAndArgs ?? 'help [command]';
                                               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

### Homebridge UI Version

4.58.0

### Homebridge Version

1.84

### Node.js Version

v20.17.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

None

### Raspberry Pi Model

None

**Comment by shanemcw** [comment]
RESOLVED
homebridge CLI was seeing an older version of node (12) than the service is (20)
