### ISSUE TITLE
Homebridge will not start

### ISSUE THREAD

**Issue by harveytcohen** [oznu/homebridge-config-ui-x#2214]
### Current Situation

When starting homebridge, it fails.  Tries to restart and continually fails.  Why, and what can be done to fix it?

### Logs

[10/26/2024, 11:17:02 AM] Error: listen EACCES: permission denied 0.0.0.0:51837
    at Server.setupListenHandle [as _listen2] (node:net:1882:21)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2063:7)
    at EventedHTTPServer.listen (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\eventedhttp.ts:166:20)
    at HAPServer.listen (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\HAPServer.ts:380:21)
    at Bridge.<anonymous> (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:1378:18)
    at step (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:196:27)
    at Object.next (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:177:57)
    at C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:170:75
    at new Promise (<anonymous>)
[10/26/2024, 11:17:02 AM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[10/26/2024, 11:17:07 AM] [HB Supervisor] Restarting Homebridge...
[10/26/2024, 11:17:07 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/26/2024, 11:17:08 AM] [HB Supervisor] Started Homebridge v1.8.5 with PID: 23684
[10/26/2024, 11:17:08 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/26/2024, 11:17:08 AM] ---
[10/26/2024, 11:17:08 AM] Loaded plugin: homebridge-config-ui-x@4.62.0
[10/26/2024, 11:17:08 AM] Registering platform 'homebridge-config-ui-x.config'
[10/26/2024, 11:17:08 AM] ---
[10/26/2024, 11:17:08 AM] Loading 1 platforms...
Setup Payload:
X-HM://0024XR8L92BLM
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 887-24-797 │     
    └────────────┘     
                       
[10/26/2024, 11:17:08 AM] Error: listen EACCES: permission denied 0.0.0.0:51837
    at Server.setupListenHandle [as _listen2] (node:net:1882:21)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2063:7)
    at EventedHTTPServer.listen (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\eventedhttp.ts:166:20)
    at HAPServer.listen (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\HAPServer.ts:380:21)
    at Bridge.<anonymous> (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:1378:18)
    at step (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:196:27)
    at Object.next (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:177:57)
    at C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:170:75
    at new Promise (<anonymous>)
[10/26/2024, 11:17:08 AM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[10/26/2024, 11:17:13 AM] [HB Supervisor] Restarting Homebridge...
[10/26/2024, 11:17:13 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/26/2024, 11:17:13 AM] [HB Supervisor] Started Homebridge v1.8.5 with PID: 2044
[10/26/2024, 11:17:14 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/26/2024, 11:17:14 AM] ---
[10/26/2024, 11:17:14 AM] Loaded plugin: homebridge-config-ui-x@4.62.0
[10/26/2024, 11:17:14 AM] Registering platform 'homebridge-config-ui-x.config'
[10/26/2024, 11:17:14 AM] ---
[10/26/2024, 11:17:14 AM] Loading 1 platforms...
Setup Payload:
X-HM://0024XR8L92BLM
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 887-24-797 │     
    └────────────┘     
                       
[10/26/2024, 11:17:14 AM] Error: listen EACCES: permission denied 0.0.0.0:51837
    at Server.setupListenHandle [as _listen2] (node:net:1882:21)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2063:7)
    at EventedHTTPServer.listen (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\eventedhttp.ts:166:20)
    at HAPServer.listen (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\HAPServer.ts:380:21)
    at Bridge.<anonymous> (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:1378:18)
    at step (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:196:27)
    at Object.next (C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:177:57)
    at C:\Users\HarveyCohen\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:170:75

### Config

```JSON
{
    "bridge": {
        "name": "Homebridge 539F",
        "username": "0E:2D:76:CC:53:9F",
        "port": 51837,
        "pin": "887-24-797",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Homebridge UI Version

unknown

### Homebridge Version

4.62.0

### Node.js Version

20.18.0

### Operating System

Windows 10

### Environment Info

None

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Your operating system, Windows is blocking access to the port required for homebridge.

**Comment by harveytcohen** [comment]
So how do I get the port unblocked???Sent from my iPhoneOn Oct 26, 2024, at 2:21 PM, Northern Man ***@***.***> wrote:﻿
Your operating system, Windows is blocking access to the port required for homebridge.
