### ISSUE TITLE
Cannot Load GUI

### ISSUE THREAD

**Issue by TheSwartz** [oznu/homebridge-config-ui-x#231]
Sorry, I'm just totally at a loss.

I use Homebridge on a Raspberry Pi (Raspbian).
I had a problem come up that seemed to totally nuke my set up.So, I completely reinstalled everything.
I re-imaged (with latest Raspbian) a new SD card for the Pi
I installed Homebridge
I installed homebridge-isy-js
I installed homebridge-config-ui-x (v3.9.6)
I'm using a bare bones config.json

**I just can't get Config to load in a browser at all.**

I've uninstalled and reinstalled per the troubleshooting.
I am using the IP address of the Raspberry Pi with port 8080
When running homebridge, I get these sorts of outputs:

Loaded config.json with 0 accessories and 2 platforms.
[3/6/2019, 6:42:10 PM] ---
[3/6/2019, 6:42:10 PM] Loaded plugin: homebridge-config-ui-x
[3/6/2019, 6:42:10 PM] Registering platform 'homebridge-config-ui-x.config'
[3/6/2019, 6:42:10 PM] ---
[3/6/2019, 6:42:10 PM] Loaded plugin: homebridge-isy-js
[3/6/2019, 6:42:10 PM] Registering platform 'homebridge-isy-js.isy-js'
[3/6/2019, 6:42:10 PM] ---
[3/6/2019, 6:42:10 PM] Loading 2 platforms...
[3/6/2019, 6:42:10 PM] [isy-js] Initializing isy-js platform...
[3/6/2019, 6:42:10 PM] [Config] Initializing config platform...
[3/6/2019, 6:42:10 PM] [Config] Spawning homebridge-config-ui-x with PID 845

and ...

[3/6/2019, 6:42:15 PM] Homebridge is running on port 51825.
[3/6/2019, 6:42:18 PM] [Config] Using Form Authentication
[3/6/2019, 6:42:18 PM] [Config] Console v3.9.6 is listening on port 8080.

So.. as far as I can tell, it's running?

**Sorry that this is a vague question, but any other ideas for troubleshooting?
Thanks!**

__________________________________
Logs:

If there are log files, I'm not sure where to find them.
__________________________________
Configuration:

config.json

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51825,
		"pin": "xxx-xx-xxx"
	},

	"description": "My Homebridge JSON file for use with ISY",

	"platforms": [{
			"platform": "isy-js",
			"name": "isy-js",
			"host": "xxx.xxx.xxx.xxx",
			"username": "xxxxx",
			"password": "xxxxxxxx",
			"elkEnabled": false,
			"useHttps": true,
			"debugLoggingEnabled": false,
			"includeAllScenes": true
		},
		{
			"platform": "config",
			"name": "Config",
			"port": 8080,
			"sudo": true,
			"restart": "sudo -n systemctl restart homebridge",
			"log": "systemd"
		}
	]
}

**Comment by TheSwartz** [comment]
I did this over again in case I messed up the first re-install

1. Imaged an SD card with Raspbian and installed to Raspberry Pi
2. Installed homebridge and homebridge-config-ui-x (no other plugins)
3. config.json
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 41687,
		"pin": "xxx-xx-xxx"
	},

	"description": "My Homebridge JSON file for use with ISY",

	"platforms": [{
		"platform": "config",
		"name": "Config",
		"port": 8080,
		"sudo": true,
		"restart": "sudo -n systemctl restart homebridge",
		"log": "systemd"
	}]
}
```
4. After a reboot, I check to see if homebridge is automatically loadeding:
```
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor prese
   Active: active (running) since Wed 2019-03-06 20:51:38 EST; 5min ago
 Main PID: 297 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─297 homebridge

Mar 06 20:51:45 raspberrypi homebridge[297]:                                    
Mar 06 20:51:45 raspberrypi homebridge[297]:                                    
Mar 06 20:51:45 raspberrypi homebridge[297]:                                    
Mar 06 20:51:45 raspberrypi homebridge[297]: Or enter this code with your HomeKi
Mar 06 20:51:45 raspberrypi homebridge[297]:                        
Mar 06 20:51:45 raspberrypi homebridge[297]:     ┌────────────┐
Mar 06 20:51:45 raspberrypi homebridge[297]:     │ xxx-xx-xxx │
Mar 06 20:51:45 raspberrypi homebridge[297]:     └────────────┘
Mar 06 20:51:45 raspberrypi homebridge[297]:                        
Mar 06 20:51:45 raspberrypi homebridge[297]: [3/6/2019, 8:51:45 PM] Homebridge i
lines 1-17/17 (END)

```
5. I try to run homebridge to see if it's loading config:
```
pi@raspberrypi:~ $ homebridge
[3/6/2019, 9:02:10 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/6/2019, 9:02:10 PM] ---
[3/6/2019, 9:02:10 PM] Loaded plugin: homebridge-config-ui-x
[3/6/2019, 9:02:10 PM] Registering platform 'homebridge-config-ui-x.config'
[3/6/2019, 9:02:10 PM] ---
[3/6/2019, 9:02:10 PM] Loading 1 platforms...
[3/6/2019, 9:02:10 PM] [Config] Initializing config platform...
[3/6/2019, 9:02:10 PM] [Config] Spawning homebridge-config-ui-x with PID 543
Setup Payload:
X-HM://0023Z59CF5MHH
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
XXXXXXXX...
XXXXXXXX...
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx │     
    └────────────┘     
                       
Error: listen EADDRINUSE: address already in use :::41687
    at Server.setupListenHandle [as _listen2] (net.js:1256:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1392:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:609:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:97:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
```
6. I assume it's not loading ("address already in use") because the service is running in the background?

**Comment by oznu** [comment]
Changes in 4.0.0 may fix your problem, otherwise checkout this guide for exactly how to get this working on Raspbian: 

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)
