### ISSUE TITLE
Ring doorbell plugin causing issues

### ISSUE THREAD

**Issue by bachoo786** [oznu/homebridge-config-ui-x#392]
**Describe Your Problem:**
Hello.

I have installed homebridge on my raspberry pi zero w using this instruction here : https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian) and it works perfectly fine.

However, when I installed the ring doorbell plugin (https://www.npmjs.com/package/homebridge-ring) for the first time everything worked fine. When I restarted my raspberry pi zero w, homebridge stopped working and has kept restarting ever since. 

If I was to remove the ringdoorbell plugin from my config.json, homebridge appears to work fine again.

Can you please help?

Thanks.

**Logs:**

```
-- Logs begin at Tue 2019-09-17 11:32:42 BST. --
Sep 17 11:36:48 raspberrypi homebridge[908]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Sep 17 11:36:48 raspberrypi homebridge[908]: [9/17/2019, 11:36:48 AM] Got SIGTERM, shutting down Homebridge...
Sep 17 11:36:53 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Sep 17 11:36:53 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Sep 17 11:36:56 raspberrypi systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Sep 17 11:36:56 raspberrypi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 7.
Sep 17 11:36:56 raspberrypi systemd[1]: Stopped Homebridge.
Sep 17 11:36:56 raspberrypi systemd[1]: homebridge.service: Found left-over process 933 (homebridge-conf) in control group while starting unit. Ignori                                       ng.
Sep 17 11:36:56 raspberrypi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Sep 17 11:36:56 raspberrypi systemd[1]: Started Homebridge.
Sep 17 11:37:24 raspberrypi homebridge[946]: [9/17/2019, 11:37:24 AM] Loaded config.json with 0 accessories and 2 platforms.
Sep 17 11:37:24 raspberrypi homebridge[946]: [9/17/2019, 11:37:24 AM] ---
Sep 17 11:37:25 raspberrypi homebridge[946]: [9/17/2019, 11:37:25 AM] Loaded plugin: homebridge-config-ui-x
Sep 17 11:37:25 raspberrypi homebridge[946]: [9/17/2019, 11:37:25 AM] Registering platform 'homebridge-config-ui-x.config'
Sep 17 11:37:25 raspberrypi homebridge[946]: [9/17/2019, 11:37:25 AM] ---
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] ====================
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] ERROR LOADING PLUGIN homebridge-ring:
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/internal/util/Unsu                                       bscriptionError.js:1
Sep 17 11:37:26 raspberrypi homebridge[946]: [2B blob data]
Sep 17 11:37:26 raspberrypi homebridge[946]: ^
Sep 17 11:37:26 raspberrypi homebridge[946]: SyntaxError: Invalid or unexpected token
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Module._compile (internal/modules/cjs/loader.js:723:23)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at require (internal/modules/cjs/helpers.js:25:18)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/internal/Subscri                                       ption.js:6:29)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] ====================
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] Loading 2 platforms...
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] [Config] Initializing config platform...
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] [Config] Spawning homebridge-config-ui-x with PID 1075
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] Error: The requested platform 'Ring' was not registered by any plugin.
Sep 17 11:37:26 raspberrypi homebridge[946]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Sep 17 11:37:26 raspberrypi homebridge[946]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] Got SIGTERM, shutting down Homebridge...
Sep 17 11:37:31 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Sep 17 11:37:31 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Sep 17 11:37:35 raspberrypi systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Sep 17 11:37:35 raspberrypi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 8.
Sep 17 11:37:35 raspberrypi systemd[1]: Stopped Homebridge.
Sep 17 11:37:35 raspberrypi systemd[1]: homebridge.service: Found left-over process 1075 (homebridge-conf) in control group while starting unit. Ignoring.
Sep 17 11:37:35 raspberrypi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Sep 17 11:37:35 raspberrypi systemd[1]: Started Homebridge.

```

```
Show the Homebridge / Homebridge Config UI X logs here.
```
I do not have access to my raspberry pi zero w as I am not at home and cannot show the logs from the UI now.

**Homebridge Config:**

```json
Show your homebridge config.json here
```

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CB:22:3D:E2:CE:31",
		"port": 51826,
		"pin": "033-44-254"
	},
	"accessories": [],
	"platforms": [{
			"name": "Config",
			"port": 8080,
			"auth": "form",
			"theme": "teal",
			"restart": "sudo -n systemctl restart homebridge",
			"tempUnits": "c",
			"sudo": true,
			"log": {
				"method": "systemd"
			},
			"platform": "config"
		},
		{
			"platform": "Ring",
			"email": "xxxxxx@hotmail.com",
			"password": "xxxxxxx"
		}
	]
}
```

**Screenshots:**

N/A
**Environment:**

* **Node.js Version**: 
v10.16.3
* **NPM Version**: 
6.9.0
* **Homebridge Version**: 
0.4.50
* **Homebridge Config UI X Version**:
latest
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
raspbian buster lite
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / other / none
systemd

**Comment by oznu** [comment]
Hi @bachoo786,

Thanks for your detailed report (and actually using the issue template).

This is the error that's causing the trouble:

```
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] ====================
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] ERROR LOADING PLUGIN homebridge-ring:
Sep 17 11:37:26 raspberrypi homebridge[946]: [9/17/2019, 11:37:26 AM] /usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/internal/util/Unsu                                       bscriptionError.js:1
Sep 17 11:37:26 raspberrypi homebridge[946]: [2B blob data]
Sep 17 11:37:26 raspberrypi homebridge[946]: ^
Sep 17 11:37:26 raspberrypi homebridge[946]: SyntaxError: Invalid or unexpected token
```

Rxjs, a dependency of homebridge-ring is failing to load. My guess is it's gotten corrupted in some way, which should easily be solved by uninstalling then immediately reinstalling that plugin. You can do this via the UI or at the command line.

**Comment by bachoo786** [comment]
Thank you for your prompt reply.

I do not have access to the UI now but hwo can I uninstall it using the command line? Sorry I am a noob and new to homebridge.

Thanks again.

**Comment by oznu** [comment]
```
# cleanup
sudo npm uninstall -g homebridge-ring

# reinstall
sudo npm install -g --unsafe-perm homebridge-ring
```

**Comment by bachoo786** [comment]
@oznu thanks alot that resolved it. I even restarted my raspberry to check if things are still working and I can confirm they are running fine.

May I ask how did the Rxjs get corrupted? Is it because I downloaded the ring plugin many times?

**Comment by oznu** [comment]
I'm not sure. SD cards can sometimes a bit flakey though.

You might be interested in setting up the UI to run in standalone mode, so you can still access the UI even if homebridge is crashing: https://github.com/oznu/homebridge-config-ui-x/wiki/Standalone-Mode#configure-standalone-mode-with-systemd.
