### ISSUE TITLE
Error: listen EADDRINUSE :::8090

### ISSUE THREAD

**Issue by maxxe88** [oznu/homebridge-config-ui-x#42]
Hi,

first of all thnk you for your great work. After I installed your Plugin I get this error in ssh:

Error: listen EADDRINUSE :::8090
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at HomebridgeConfigUi.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/src/index.ts:39:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/index.js:4:58)
    at <anonymous>

Is there any sollution?

**Comment by oznu** [comment]
Hi @maxxe88,

Another process on your computer is using port 8090, or you have multiple instances of Homebridge running.

If another process is using port 8090 the solution is to pick a different port.

**Comment by maxxe88** [comment]
I tried to change the port. Same problem. I trie it again.

**Comment by maxxe88** [comment]
Error: listen EADDRINUSE :::8088
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at HomebridgeConfigUi.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/src/index.ts:39:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/index.js:4:58)
    at <anonymous>

Is there any Plugin or something which uses the same Port as the GUi Plugin,

**Comment by oznu** [comment]
Can you show me the output of this command?

```
# Linux
sudo netstat -tulpn | grep "LISTEN" | grep "8090"

# macOS
lsof -i -P -n | grep LISTEN | grep "8090"
```

**Comment by maxxe88** [comment]
pi@raspberrypi:~ $ sudo netstat -tulpn | grep "LISTEN" | grep "8088"
tcp6       0      0 :::8088                 :::*                    LISTEN      515/homebridge  

I use the 8088 because i tried another change of the port.

**Comment by oznu** [comment]
Please run this:

```
sudo killall homebridge
```

Then start homebridge again provide the full Homebridge log output so I can see what's going on for you.

**Comment by maxxe88** [comment]
Where can I find the log?

**Comment by oznu** [comment]
The same place you're getting that error output from :)

**Comment by maxxe88** [comment]
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-3-3 11:13:40] Loaded plugin: homebridge-config-ui-x
[2018-3-3 11:13:40] Registering platform 'homebridge-config-ui-x.config'
[2018-3-3 11:13:40] ---
[2018-3-3 11:13:44] Loaded plugin: homebridge-hue
[2018-3-3 11:13:44] Registering platform 'homebridge-hue.Hue'
[2018-3-3 11:13:44] ---
[2018-3-3 11:13:45] Loaded plugin: homebridge-hyperion-light
[2018-3-3 11:13:45] Registering accessory 'homebridge-hyperion.Hyperion'
[2018-3-3 11:13:45] ---
[2018-3-3 11:13:45] Loaded config.json with 1 accessories and 2 platforms.
[2018-3-3 11:13:45] ---
[2018-3-3 11:13:45] Loading 2 platforms...
[2018-3-3 11:13:45] [Hue] Initializing Hue platform...
[2018-3-3 11:13:45] [Hue] homebridge-hue v0.8.1, node v8.9.4, homebridge v0.4.38
[2018-3-3 11:13:45] [Config] Initializing config platform...
[2018-3-3 11:13:45] Loading 1 accessories...
[2018-3-3 11:13:45] [Beleuchtung] Initializing Hyperion accessory...
[2018-3-3 11:13:51] [Config] Using Form Authentication
[2018-3-3 11:13:51] [Config] Console is listening on port 8090.
[2018-3-3 11:13:51] [Hue] npm registry: communication error ETIMEDOUT on https://registry.npmjs.org/
[2018-3-3 11:13:51] [Beleuchtung] Version check for homebridge-hyperion-light
[2018-3-3 11:13:51] [Beleuchtung] npm version is 1.1.4, your local version is 1.1.4
[2018-3-3 11:13:51] [Hue] dresden appspot ipv6: communication error ENETUNREACH on https://dresden-light.appspot.com/
[2018-3-3 11:13:56] [Hue] Philips hue: BSB002 bridge v1801260942, api v1.23.0
[2018-3-3 11:13:56] [Hue] Philips hue: /lights/6: warning: using default colour temperature range for unknown light model {"state":{"on":false,"bri":25,"hue":1200,"sat":248,"effect":"none","xy":[0.5048,0.4137],"ct":447,"alert":"none","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Extended color light","name":"Glühbirne","modelid":"RB 185 C","manufacturername":"innr","capabilities":{"certified":false,"streaming":{"renderer":false,"proxy":false}},"uniqueid":"00:15:8d:00:01:96:b7:de-01","swversion":"2.0"}
[2018-3-3 11:13:56] [Hue] Philips hue: 3 accessories
[2018-3-3 11:13:56] [Hue] masked debug info dumped to /home/pi/.homebridge/homebridge-hue.json.gz
[2018-3-3 11:13:56] [Hue] Initializing platform accessory 'Philips hue'...
[2018-3-3 11:13:56] [Hue] Philips hue: 3 services
[2018-3-3 11:13:56] [Hue] Initializing platform accessory 'Glühbirne'...
[2018-3-3 11:13:56] [Hue] Initializing platform accessory 'Steckdose'...
Setup Payload:
X-HM://0023OA632DD29
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       

                       
[2018-3-3 11:13:57] Homebridge is running on port 51826.

**Comment by maxxe88** [comment]
When I kill the homebridge and start it again it works.

**Comment by oznu** [comment]
Great, there must have been some instance of homebridge running in the background. Glad it's working for you now.

**Comment by maxxe88** [comment]
Thank you very much. Can you maybe help me with the hue issue? I've never seen it before.

**Comment by oznu** [comment]
You're welcome. I don't run the Hue plugin so probably won't be much help. The author is very proactive at responding to issues here though: https://github.com/ebaauw/homebridge-hue/issues

**Comment by maxxe88** [comment]
Great, thank you. One question. Would it be possible to show the changelog of the updateable plugins?

**Comment by oznu** [comment]
That would be a great inclusion, unfortunately there is no constant way in which the authors of npm packages display their change log. Some use GitHub release notes, others a `CHANGELOG` file, some a the bottom of the `README` and others don't bother at all (like this repo).

**Comment by maxxe88** [comment]
Oh ok, can you write an Changelog everytime?
