### ISSUE TITLE
Error updating..

### ISSUE THREAD

**Issue by leendersf** [oznu/homebridge-config-ui-x#457]
**Describe Your Problem:**

Error: EACCES: permission denied, mkdir '/homebridge/persist'
    at Object.mkdirSync (fs.js:823:3)
    at Function.sync (/usr/local/lib/node_modules/homebridge/node_modules/mkdirp/index.js:71:13)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:642:20)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/homebridge/persist'
}
**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

Timezone | GMT+0000
-- | --
Alpine Linux (3.10.3)
raspberrypi
10.0.1.201
fdc4:798e:e8e6:1:89bc:aabc:1af5:90a2
v12.14.0
root
/homebridge
/homebridge/config.json
/homebridge/node_modules
Yes

**Homebridge Config:**
{
    "bridge": {
        "name": "Homebridge 8C69",
        "username": "0E:82:B8:B8:8C:69",
        "port": 51014,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": false
        }
    ]
}
```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by leendersf** [comment]
I installed using sudo npm install -g --unsafe-perm homebridge-config-ui-x and through the update link in the plugin area.

I run in Docker. But still this error. All other plugins not showing and my old config + backups are gone.. Can anyone help me? Thank you very much!

**Comment by leendersf** [comment]
I don't know what I did but now it seems to work!!!
