### ISSUE TITLE
Cannot find module '../build/Debug/pty.node'

### ISSUE THREAD

**Issue by JonoHaysom** [oznu/homebridge-config-ui-x#484]
Hi guys, ive updated Node.js and now have the below issue. can anyone help me troubleshoot this please?

node -v = v13.6.0
npm -v = 6.13.4

ive tried uninstalling via "sudo npm uninstall -g homebridge-config-ui-x" and reinstalling via "sudo npm install -g --unsafe-perm homebridge-config-ui-x" but without any luck. 

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js'
  ]
}
[17/01/2020, 17:13:50] [Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 79. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
[17/01/2020, 17:13:50] [Config] [node-pty] Node.js v13.6.0
[17/01/2020, 17:13:50] [Config] [node-pty] Failed to load node-pty module
[17/01/2020, 17:13:50] [Config] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version and have not reinstalled or rebuilt this plugin.
[17/01/2020, 17:13:50] [Config] [node-pty] This can usually be fixed by uninstalling and reinstalling this plugin (exact command may vary based on your platform and setup):
[17/01/2020, 17:13:50] [Config] [node-pty] sudo npm uninstall -g homebridge-config-ui-x
[17/01/2020, 17:13:50] [Config] [node-pty] sudo npm install -g --unsafe-perm homebridge-config-ui-x
[17/01/2020, 17:13:50] Got SIGTERM, shutting down Homebridge...

**Comment by oznu** [comment]
Post the output from this if it doesn't fix the problem:

```
cd $(npm -g prefix)/lib/node_modules
sudo npm rebuild
```

**Comment by JonoHaysom** [comment]
> Post the output from this if it doesn't fix the problem:
> 
> ```
> cd $(npm -g prefix)/lib/node_modules
> sudo npm rebuild
> ```

Thank you for helping me with your expertise. you've made my day!
