### ISSUE TITLE
CONTRIBUTING

### ISSUE THREAD

**Issue by LaborEtArs** [oznu/homebridge-config-ui-x#498]
As I really like this tool, I decided to add two controls for 'Speaker' and 'Battery Service', but... this seems to be the most complicated github project to contribute to I ever met...
First (not having read your contributing.md file) I just cloned the repo from github, created the new files and integrated them into the system. When trying to test them, I found out, that the installed version is a compilation of sources and not (like most other homebridge-plugin projects), just a node.js project.
Then, after reading your 'contributing' doc, I tried to use my Raspi PI Zero installation to setup the development environment, only to find out, that the installed node version (9.9.0, Raspi PI Zero->armv6) isn't supported anymore by the build tools.
In a third step I took a OrangePi Zero (512 MB RAM, armv7), but without success so far. Everytime I do call 'npm run build', after a few minutes I get a 'JavaScript heap out of memory' message (see below). I already installed a swapfile, flushed caches and buffer, ... but to no avail.
Are there any tips to build the development environment on a small system like Raspberry?

[homebridge-config-ui-x build dev env log.txt](https://github.com/oznu/homebridge-config-ui-x/files/4089727/homebridge-config-ui-x.build.dev.env.log.txt)

**Comment by LaborEtArs** [comment]
node -v. ->  v12.14.1
npm -v  ->  6.13.4

**Comment by oznu** [comment]
Hi @LaborEtArs,

A raspberry pi will not have enough memory or cpu power to do live development on this project - I don't think it would be workable even on a Raspberry Pi 4 with 4GB ram.

**Comment by LaborEtArs** [comment]
@onzu Oh, thanks for pointing out this. Might be worth to mention in 'contributing.md' as many user do use a Raspi to drive homebridge on, I'd guess.

**Comment by mafyata** [comment]
I have installed node v10 on raspberry pi zero w , working homebridge and config ui x

sudo su
curl -sL https://deb.nodesource.com/setup_10.x | bash -
sudo apt-get install -y nodejs

**Comment by LaborEtArs** [comment]
@mafyata Thank for the info, but running homebridge, homebridge-config-ui-x, ... on a raspi pi zero isn't the problem. The problem arises when trying to setup the development environment for homebridge-config-ui-x (an angular/typescript project).

**Comment by mafyata** [comment]
Yes , I wanted to tell you that nodejs 10 and 11 are working on p zero w. Last version that works for me is v11.15.0

**Comment by mafyata** [comment]
I see your version is 9

**Comment by LaborEtArs** [comment]
@onzu Installed homebridge and the dev env on my Mac now. Got it up until login to localhost:4200. After login something crashes:
[1] dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
[1]   Referenced from: /usr/local/bin/awk
[1]   Reason: image not found
[1] /bin/sh: line 1: 41369 Done                    route get 0.0.0.0 2> /dev/null
[1]      41370 Broken pipe: 13         | grep interface:
[1]      41371 Abort trap: 6           | awk '{print $2}'
[1] Error: Command failed: route get 0.0.0.0 2>/dev/null | grep interface: | awk '{print $2}'
[1] dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
[1]   Referenced from: /usr/local/bin/awk
[1]   Reason: image not found
[1] /bin/sh: line 1: 41369 Done                    route get 0.0.0.0 2> /dev/null
[1]      41370 Broken pipe: 13         | grep interface:
[1]      41371 Abort trap: 6           | awk '{print $2}'
[1] 
[1]     at checkExecSyncError (child_process.js:611:11)
[1]     at execSync (child_process.js:647:15)
[1]     at getDefaultNetworkInterface (/Users/hartmut/Homebridge_Projekte/homebridge-config-ui-x/node_modules/systeminformation/lib/network.js:96:18)
[1]     at /Users/hartmut/Homebridge_Projekte/homebridge-config-ui-x/node_modules/systeminformation/lib/network.js:175:20
[1]     at processTicksAndRejections (internal/process/task_queues.js:79:11)
[1] [nodemon] app crashed - waiting for file changes before starting...

Any idea?

**Comment by oznu** [comment]
Do you have `brew` installed?
 
If so, try this https://stackoverflow.com/questions/40240938/dyld-library-not-loaded-referenced-from-usr-local-bin-awk

**Comment by LaborEtArs** [comment]
Thumbs up! Worked :-)

**Comment by oznu** [comment]
Added note to contributing.md:

> Note: The Raspberry Pi and similar boards do not meet the memory or CPU requirements required to setup the development environment.
