### ISSUE TITLE
HB Service - ESOCKETTIMEDOUT error

### ISSUE THREAD

**Issue by kimme1024** [oznu/homebridge-config-ui-x#516]
**Describe Your Problem:**
When using homebridge as a service I'm getting ESOCKETTIMEDOUT error for both my plugins.
While I can login into the WebUI my temperature sensors aren't giving any response. 

However when I use homebridge standalone in a screen everything works perfectly.

**Logs:**

```
[1/31/2020, 11:39:51] Loaded config.json with 3 accessories and 1 platforms.
[1/31/2020, 11:39:51] ---
[1/31/2020, 11:39:51] Loaded plugin: homebridge-config-ui-x
[1/31/2020, 11:39:51] Registering platform 'homebridge-config-ui-x.config'
[1/31/2020, 11:39:51] ---
[1/31/2020, 11:39:51] Loaded plugin: homebridge-mi-hygrothermograph
[1/31/2020, 11:39:51] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-config-ui-x'.
[1/31/2020, 11:39:51] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-mi-hygrothermograph' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-mi-hygrothermograph'.
[1/31/2020, 11:39:53] [Config] Homebridge Config UI X v4.9.0 is listening on :: port 8581
[1/31/2020, 11:39:53] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[1/31/2020, 11:39:53] ---
[1/31/2020, 11:39:53] Loading 1 platforms...
[1/31/2020, 11:39:53] [Config] Initializing config platform...
[1/31/2020, 11:39:53] [Config] Running in Standalone Mode.
[1/31/2020, 11:39:53] Loading 3 accessories...
[1/31/2020, 11:39:53] [Slaapkamer] Initializing Hygrotermograph accessory...
[1/31/2020, 11:39:54] [Badkamer] Initializing Hygrotermograph accessory...
[1/31/2020, 11:39:54] [Fitness] Initializing Hygrotermograph accessory...
Setup Payload:
X-HM://0023ISYWY4A2A
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/31/2020, 11:39:54] Homebridge is running on port 51826.
[1/31/2020, 11:39:54] [Slaapkamer] Start scanning.
[1/31/2020, 11:39:54] [Badkamer] Start scanning.
[1/31/2020, 11:39:54] [Fitness] Start scanning.
[1/31/2020, 11:40:06] [Config] [homebridge-config-ui-x] Error: ETIMEDOUT
[1/31/2020, 11:40:06] [Config] [homebridge-mi-hygrothermograph] Error: ETIMEDOUT
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
        {
            "accessory": "Hygrotermograph",
            "name": "Slaapkamer",
            "address": "4C:65:A8:D7:94:03",
            "fakeGatoEnabled": "true"
        },
        {
            "accessory": "Hygrotermograph",
            "name": "Badkamer",
            "address": "4C:65:A8:D8:54:24",
            "fakeGatoEnabled": "true"
        },
        {
            "accessory": "Hygrotermograph",
            "name": "Fitness",
            "address": "4C:65:A8:DC:88:41",
            "fakeGatoEnabled": "true"
        }
    ],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8581
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 12.14.1
* **NPM Version**: 6.13.4
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.9.0
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
The logs suggest you have multiple versions of Node.js installed using different methods.

When you run Homebridge manually are you doing so as the same service user you defined when running the `hb-service install` command?

**Comment by kimme1024** [comment]
Hi,

I've seen that as well but I'm getting the same error in my standalone homebridge instance where it doesn't affect it.
When I run it manually I'm running it as the standard user (pi) in a screen using `homebridge -I`
When I install the hb-service I'm using `sudo hb-service install --user pi` so I'm assuming that should be ok.
FYI, I'm not really experienced in all this. I just set up everything using info spread around online so I guess my setup isn't the cleanest one you can find...

**Comment by oznu** [comment]
Do you experience the same symptoms running this command as the pi user:

`hb-service run -I -U /var/lib/homebridge`

**Comment by kimme1024** [comment]
Exactly the same. It runs, I can login to the WebUI but my sensors won't update.

**Comment by oznu** [comment]
Try this for me.

Start the service using hb-service.
Wait 2-3 minutes.
Run `kill -15 $(pidof homebridge)`
Wait for homebridge to restart itself (don't manually restart the service).
Check if the symptoms persist.

Are you running a Raspberry Pi 1 or Zero?

**Comment by kimme1024** [comment]
This time when starting the service I didn't get the sockettimedout message.
When I ran your command it restarted but nothing really changed.
The sensors are still down.
I'm running an RPi3

```
[1/31/2020, 13:49:03] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[1/31/2020, 13:49:03] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[1/31/2020, 13:49:03] [HB Supervisor] Started Homebridge with PID: 29444
[1/31/2020, 13:49:05] Loaded config.json with 3 accessories and 1 platforms.
[1/31/2020, 13:49:05] ---
[1/31/2020, 13:49:05] Loaded plugin: homebridge-config-ui-x
[1/31/2020, 13:49:05] Registering platform 'homebridge-config-ui-x.config'
[1/31/2020, 13:49:05] ---
[1/31/2020, 13:49:05] Loaded plugin: homebridge-mi-hygrothermograph
[1/31/2020, 13:49:05] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-config-ui-x'.
[1/31/2020, 13:49:05] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-mi-hygrothermograph' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-mi-hygrothermograph'.
[1/31/2020, 13:49:08] [Config] Homebridge Config UI X v4.9.0 is listening on :: port 8581
[1/31/2020, 13:49:08] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[1/31/2020, 13:49:08] ---
[1/31/2020, 13:49:08] Loading 1 platforms...
[1/31/2020, 13:49:08] [Config] Initializing config platform...
[1/31/2020, 13:49:08] [Config] Running in Standalone Mode.
[1/31/2020, 13:49:08] Loading 3 accessories...
[1/31/2020, 13:49:08] [Slaapkamer] Initializing Hygrotermograph accessory...
[1/31/2020, 13:49:08] [Badkamer] Initializing Hygrotermograph accessory...
[1/31/2020, 13:49:08] [Fitness] Initializing Hygrotermograph accessory...
Setup Payload:
X-HM://0023ISYWY4A2A
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/31/2020, 13:49:08] Homebridge is running on port 51826.
[1/31/2020, 13:49:08] [Slaapkamer] Start scanning.
[1/31/2020, 13:49:08] [Badkamer] Start scanning.
[1/31/2020, 13:49:08] [Fitness] Start scanning.
[1/31/2020, 13:49:35] [Config] Multiple Instances Of Homebridge Found Installed
[1/31/2020, 13:49:35] [Config] /usr/local/lib/node_modules/homebridge
[1/31/2020, 13:49:35] [Config] /usr/lib/node_modules/homebridge
[1/31/2020, 13:51:22] [Config] Multiple Instances Of Homebridge Found Installed
[1/31/2020, 13:51:22] [Config] /usr/local/lib/node_modules/homebridge
[1/31/2020, 13:51:22] [Config] /usr/lib/node_modules/homebridge
[1/31/2020, 13:52:22] Got SIGTERM, shutting down Homebridge...
[1/31/2020, 13:52:23] [Config] Multiple Instances Of Homebridge Found Installed
[1/31/2020, 13:52:23] [Config] /usr/local/lib/node_modules/homebridge
[1/31/2020, 13:52:23] [Config] /usr/lib/node_modules/homebridge
[1/31/2020, 13:52:27] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/31/2020, 13:52:32] [HB Supervisor] Restarting Homebridge...
[1/31/2020, 13:52:32] [HB Supervisor] Started Homebridge with PID: 29947
[1/31/2020, 13:52:34] Loaded config.json with 3 accessories and 1 platforms.
[1/31/2020, 13:52:34] ---
[1/31/2020, 13:52:34] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-config-ui-x'.
[1/31/2020, 13:52:34] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-mi-hygrothermograph' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-mi-hygrothermograph'.
[1/31/2020, 13:52:34] Loaded plugin: homebridge-config-ui-x
[1/31/2020, 13:52:34] Registering platform 'homebridge-config-ui-x.config'
[1/31/2020, 13:52:34] ---
[1/31/2020, 13:52:34] Loaded plugin: homebridge-mi-hygrothermograph
[1/31/2020, 13:52:37] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[1/31/2020, 13:52:37] ---
[1/31/2020, 13:52:37] Loading 1 platforms...
[1/31/2020, 13:52:37] [Config] Initializing config platform...
[1/31/2020, 13:52:37] [Config] Running in Standalone Mode.
[1/31/2020, 13:52:37] Loading 3 accessories...
[1/31/2020, 13:52:37] [Slaapkamer] Initializing Hygrotermograph accessory...
[1/31/2020, 13:52:37] [Badkamer] Initializing Hygrotermograph accessory...
[1/31/2020, 13:52:37] [Fitness] Initializing Hygrotermograph accessory...
Setup Payload:
X-HM://0023ISYWY4A2A
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/31/2020, 13:52:37] Homebridge is running on port 51826.
[1/31/2020, 13:52:37] [Slaapkamer] Start scanning.
[1/31/2020, 13:52:37] [Badkamer] Start scanning.
[1/31/2020, 13:52:37] [Fitness] Start scanning.
```

**Comment by doczelig** [comment]
hi,
exactly same problems as  kimme1024.
I'm following you.
Pi Zero W here

**Comment by oznu** [comment]
@kimme1024 

Can you show me the log output from running homebridge manually?

**Comment by kimme1024** [comment]
```
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
 
    ┌────────────┐
    │ 031-45-154 │
    └────────────┘
 
[1/31/2020, 13:55:18] Homebridge is running on port 51826.
[1/31/2020, 13:55:18] [Slaapkamer] Start scanning.
[1/31/2020, 13:55:18] [Badkamer] Start scanning.
[1/31/2020, 13:55:18] [Fitness] Start scanning.
[1/31/2020, 13:55:23] [Config] Homebridge Config UI X v4.9.0 is listening on :: port 9090
[2/1/2020, 10:33:15] [Badkamer] Error: Unknown event type: 16. 5020aa01a82454d8a8654c100004ac008c02
    at Parser.parseEventData (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:174:15)
    at Parser.parse (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:56:23)
    at Scanner.parseServiceData (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:164:38)
    at Scanner.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:90:25)
    at Noble.emit (events.js:228:7)
    at Noble.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:178:10)
    at NobleBindings.emit (events.js:223:5)
    at NobleBindings.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:174:10)
    at Gap.emit (events.js:223:5)
    at Gap.onHciLeAdvertisingReport (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/gap.js:256:10)
[2/1/2020, 15:59:40] [Config] Multiple Instances Of Homebridge Found Installed
[2/1/2020, 15:59:40] [Config] /usr/local/lib/node_modules/homebridge
[2/1/2020, 15:59:40] [Config] /usr/lib/node_modules/homebridge
[2/1/2020, 16:31:20] [Config] Multiple Instances Of Homebridge Found Installed
[2/1/2020, 16:31:20] [Config] /usr/local/lib/node_modules/homebridge
[2/1/2020, 16:31:20] [Config] /usr/lib/node_modules/homebridge
[2/2/2020, 10:07:02] [Badkamer] Error: Unknown event type: 1037. 5020aa01cc2454d8a8654c0d0400a7007802
    at Parser.parseEventData (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:174:15)
    at Parser.parse (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:56:23)
    at Scanner.parseServiceData (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:164:38)
    at Scanner.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:90:25)
    at Noble.emit (events.js:228:7)
    at Noble.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:178:10)
    at NobleBindings.emit (events.js:223:5)
    at NobleBindings.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:174:10)
    at Gap.emit (events.js:223:5)
    at Gap.onHciLeAdvertisingReport (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/gap.js:256:10)
```

Don't really know what causes the errors for the sensors but they keep on working so nothing critical I guess...
