### ISSUE TITLE
Noob issue homebridge ‘not running’ in UI after reboot

### ISSUE THREAD

**Issue by L4RGER** [oznu/homebridge-config-ui-x#557]
Hi, 
Please forgive me if this is incorrect. I’m trying. 
I’m new to all this, yesterday I set up homebridge and config-ui-x, I restarted the Rpi through the ui. Since then the ui has only shown the homebridge as not running. I checked homebridge status through systemctl status homebridge and it’s active. I think I’ve since got another instance of homebridge running as I typed ‘homebridge’ in terminal. 
I’ve added a bunch of plugins, without devices yet. The only device I’ve added is a tuya light.

**Logs:**
Not sure if you want a copy and paste or screenshot 
Here’s a screen shot of the UI logs
![16B00BA5-5C92-444F-9C8C-FC3E1736D989](https://user-images.githubusercontent.com/61365310/75100837-e6d5cb80-561e-11ea-8f90-2379e525b261.jpeg)

**Homebridge Config:**
I can copy and paste full config if required but here’s a screenshot
![7ACD4B1E-A9C6-40A7-903C-D1F8ABEFD05D](https://user-images.githubusercontent.com/61365310/75100841-f6edab00-561e-11ea-9e41-02b2d5c06244.jpeg)

**Screenshots:**
![CB481C29-C74C-4231-B1E7-26BBC11579B8](https://user-images.githubusercontent.com/61365310/75100858-2997a380-561f-11ea-8ecb-3efd1520fd03.jpeg)

**Environment:**

* **Node.js Version**: V10.15.2
* **NPM Version**: 6.13.7
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.10.3
* **Operating System**: Raspbian 
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
I need the full logs. The error is just out of the viewport in your screen shot.

`hb-service logs`

**Comment by L4RGER** [comment]
[2/23/2020, 10:44:43 AM] Loaded plugin: homebridge-tuya-lan2
[2/23/2020, 10:44:43 AM] Registering platform 'homebridge-tuya-lan.TuyaLan'
[2/23/2020, 10:44:43 AM] ---
[2/23/2020, 10:44:43 AM] ====================
[2/23/2020, 10:44:43 AM] ERROR LOADING PLUGIN homebridge-wiz-lan:
[2/23/2020, 10:44:43 AM] /usr/local/lib/node_modules/homebridge-wiz-lan/lib/client/index.js:256
  setPilot = (host, state) => {
           ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[2/23/2020, 10:44:43 AM] ====================
[2/23/2020, 10:44:43 AM] ====================
[2/23/2020, 10:44:43 AM] ERROR LOADING PLUGIN homebridge-zigbee-v2:
[2/23/2020, 10:44:43 AM] Error: Cannot find module '../model/group'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-zigbee-v2/node_modules/zigbee-shepherd/lib/components/af.js:17:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[2/23/2020, 10:44:43 AM] ====================
[2/23/2020, 10:44:43 AM] Loading 4 platforms...
[2/23/2020, 10:44:43 AM] [Config] Initializing config platform...
[2/23/2020, 10:44:43 AM] [Config] Running in Standalone Mode.
[2/23/2020, 10:44:43 AM] [Hue] Initializing Hue platform...
[2/23/2020, 10:44:43 AM] [Hue] homebridge-hue v0.11.55, node v10.15.2, homebridge v0.4.50
[2/23/2020, 10:44:43 AM] [Hue] warning: not using recommended node version v12.16.1 LTS
[2/23/2020, 10:44:43 AM] Error: The requested platform 'ZigBeePlatform' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:17435) ExperimentalWarning: The fs.promises API is experimental
[2/23/2020, 10:44:43 AM] [Hue] npm registry: events.once is not a function
[2/23/2020, 10:44:43 AM] [Hue] searching bridges and gateways
[2/23/2020, 10:44:43 AM] [Hue] events.once is not a function
[2/23/2020, 10:44:43 AM] [Hue] TypeError: (intermediate value) is not iterable
    at HuePlatform.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:303:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2/23/2020, 10:44:43 AM] Got SIGTERM, shutting down Homebridge...
[2/23/2020, 10:44:48 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/23/2020, 10:44:53 AM] [HB Supervisor] Restarting Homebridge...
[2/23/2020, 10:44:53 AM] [HB Supervisor] Started Homebridge with PID: 17492
[2/23/2020, 10:44:58 AM] Loaded config.json with 0 accessories and 4 platforms.
[2/23/2020, 10:44:58 AM] ---
[2/23/2020, 10:44:58 AM] Loaded plugin: homebridge-config-ui-x
[2/23/2020, 10:44:58 AM] Registering platform 'homebridge-config-ui-x.config'
[2/23/2020, 10:44:58 AM] ---
[2/23/2020, 10:44:58 AM] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^12.16.1 which does not satisfy the current Node version of v10.15.2. You may need to upgrade your installation of Node.
[2/23/2020, 10:45:00 AM] Loaded plugin: homebridge-hue
[2/23/2020, 10:45:00 AM] Registering platform 'homebridge-hue.Hue'
[2/23/2020, 10:45:00 AM] ---
[2/23/2020, 10:45:00 AM] Loaded plugin: homebridge-sengled
[2/23/2020, 10:45:00 AM] Registering platform 'homebridge-sengled.SengledHub'
[2/23/2020, 10:45:00 AM] ---
[2/23/2020, 10:45:01 AM] Loaded plugin: homebridge-smartthings-v2
[2/23/2020, 10:45:01 AM] Registering platform 'homebridge-smartthings-v2.SmartThings-v2'
[2/23/2020, 10:45:01 AM] ---
[2/23/2020, 10:45:01 AM] Loaded plugin: homebridge-tuya-lan2
[2/23/2020, 10:45:01 AM] Registering platform 'homebridge-tuya-lan.TuyaLan'
[2/23/2020, 10:45:01 AM] ---

**Comment by oznu** [comment]
This is a plugin issue as per the logs.

`homebridge-zigbee-v2` is causing you problems. Did you mean to install `-v2`?

Check your config matches the instructions for the plugin, otherwise you should raise the issue on that plugins project page.

**Comment by L4RGER** [comment]
I’ve just uninstalled that one and wiz 
I’ll do a reboot and see

**Comment by L4RGER** [comment]
Also thank you for the quick responses. I went for v2 because it was newer. I’d hoped to set up home bridge prior to buying devices, to save time. 
Probably not the best way to do it

**Comment by oznu** [comment]
I'm not familiar with either of the  `homebridge-zigbee` plugins so can't help much in that department.

If Homebridge is ever "Not Running" just check the logs, usually the error will be in red text and if you read carefully you'll see the name of the plugin in it somewhere.

**Comment by L4RGER** [comment]
All sorted after I removed those plugins and rebooted.
