### ISSUE TITLE
shutdown Homebridge after a while

### ISSUE THREAD

**Issue by Donni1966** [oznu/homebridge-config-ui-x#583]
Hi, 
i am running the version 4.10.3 an try it also with 4.12 but after a while the homebrigde stopps with the last comment in homebridge.err 
[0;37m[07/03/2020, 19:51:53] [0m[0;36m[ConfigPi3][0m [0;31mRequestError: Error: socket hang up[0m
[0;37m[07/03/2020, 19:51:53] [0m[0;36m[ConfigPi3][0m [0;31mCaught Unhandled Rejection Error :: Details Below[0m
RequestError: Error: socket hang up
    at new RequestError (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:321:20)
    at Socket.socketOnEnd (_http_client.js:463:9)
    at Socket.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12) {
  name: 'RequestError',
  message: 'Error: socket hang up',
  cause: Error: socket hang up
      at connResetException (internal/errors.js:609:14)
      at Socket.socketOnEnd (_http_client.js:463:23)
      at Socket.emit (events.js:333:22)
      at endReadableNT (_stream_readable.js:1201:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  },
  error: Error: socket hang up
      at connResetException (internal/errors.js:609:14)
      at Socket.socketOnEnd (_http_client.js:463:23)
      at Socket.emit (events.js:333:22)
      at endReadableNT (_stream_readable.js:1201:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  },
  options: {
    qs: { id: '212.45,212.46,212.47,212.48,212.49' },
    json: true,
    uri: 'http://192.168.2.103:51826/characteristics',
    method: 'GET',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

any idear?

i am not a beginner, but not the best in reading log files .. and understand it :-)

**Comment by oznu** [comment]
I've updated the hap-client dependency to catch these errors now so it shouldn't crash the UI process when the connections for accessory control disconnect.

Currently in `@test` and will be live in next weeks release.

See this page for details on how to install test versions: https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by Donni1966** [comment]
Thanx - i install it, will test now. 

great work!
