### ISSUE TITLE
can you help with this Error Oznu?

### ISSUE THREAD

**Issue by henkied** [oznu/homebridge-config-ui-x#60]
Hi @oznu i have an issue with ffmpeg, i have installed homebridge on a synology 

I have the same error with the omx version

I get this error:

2018-3-17 13:38:12] [Camera-ffmpeg] Snapshot from TEST at 480x270
Error: spawn ffmpeg ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-3-17 13:38:17] Loaded plugin: homebridge-camera-ffmpeg
[2018-3-17 13:38:17] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'

**Comment by oznu** [comment]
Hi @henkied,

Issues related to docker should be posted on this repo: https://github.com/oznu/docker-homebridge#3-need-ffmpeg

You shouldn't use the omx version on Synology. The error suggests you don't have ffmpeg installed.

**Comment by henkied** [comment]
ow sorry i will post him there,

ffmpeg is installed
