### ISSUE TITLE
Can't get plugin to start

### ISSUE THREAD

**Issue by fullphat** [oznu/homebridge-config-ui-x#629]
**Describe Your Problem:**

Installed plugin and edited `config.json` accordingly.  When I launch Homebridge, it doesn't seem to load the plugin and I get the following error:

```
[4/22/2020, 08:59:53] Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[4/22/2020, 08:59:54] Got SIGTERM, shutting down Homebridge...
```

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json

"platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": false
    }
]

```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
v12.16.2

* **NPM Version**: 
6.14.4

* **Homebridge Version**: 
0.4.53

* **Homebridge Config UI X Version**:

* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
Raspbian Jesse

* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
none

**Comment by oznu** [comment]
Your logs suggest the UI was not installed; or you have multiple copies of Node.js running which is causing strange things to happen.

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by fullphat** [comment]
Thanks for replying!

That's how I installed the plugin originally.  Ran the command again - this is the output:

```
pi@study:~/.homebridge $ sudo kill 11176
[4/22/2020, 09:34:23] Got SIGTERM, shutting down Homebridge...
pi@study:~/.homebridge $ sudo npm install -g --unsafe-perm homebridge-config-ui-x
/usr/local/bin/homebridge-config-ui-x -> /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
/usr/local/bin/hb-service -> /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
+ homebridge-config-ui-x@4.16.0
updated 1 package in 136.633s
[1]+  Exit 143                homebridge -U /home/pi/.homebridge
pi@study:~/.homebridge $ 
```

Still the same error I'm afraid:

```
[4/22/2020, 09:40:17] Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

Anything else I can try?

Do I need `hb-service` to be running?

**Comment by oznu** [comment]
It looks like you have a copy of node at two locations:

`/usr/bin/node` and `/usr/local/bin/node`.

It
Might be easier if you message me on the Homebridge Discord, then I can walk you through fixing everything up.

**Comment by oznu** [comment]
I just wrote this guide up, as I've had a few similar issues recently as people upgrade their old installs.

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux
