### ISSUE TITLE
Updated to 4.18.0 and system will not start after reboot

### ISSUE THREAD

**Issue by sethfox** [oznu/homebridge-config-ui-x#666]
I Updated homebridge-config-ui-x to 4.18.0 and system will not start after reboot

I have installed homebridge from the raspberry pi image yesterday. Saw the config-ui-x update this mprming so I installed it. Install seemed to work OK. Tried to reboot the pi to make sure everything started up OK from boot and I get the errors detailed below.
**Logs:**

```
[5/7/2020, 08:34:21] [HB Supervisor] OS: Linux 4.19.97-v7+ arm
[5/7/2020, 08:34:21] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[5/7/2020, 08:34:21] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[5/7/2020, 08:34:21] [HB Supervisor] Starting Homebridge with extra flags: -I
[5/7/2020, 08:34:21] [HB Supervisor] Started Homebridge v1.0.4 with PID: 3367
[5/7/2020, 08:34:23] [HB Supervisor] ERROR: The user interface threw an unhandled error
/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/rxjs/internal/BehaviorSubject.js:3
(   var0e|tendStatics = nunction (`, b) {
    ^^^^^^^^^^^^^^^^^

SyntaxError: Invalid left-hand side in assignment
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/rxjs/index.js:13:25)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
[5/7/2020, 08:34:23] Loaded config.json with 0 accessories and 2 platforms.
[5/7/2020, 08:34:23] ---
[5/7/2020, 08:34:23] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 283F",
        "username": "0E:9C:D2:2A:28:3F",
        "port": 51388,
        "pin": "622-89-472"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "Hubitat-MakerAPI",
            "name": "Hubitat",
            "app_url": "http://REMOVED/apps/api/257/",
            "access_token": "REMOVED",
            "local_ip": "REMOVED",
            "local_port": 20010,
            "polling_seconds": 300,
            "temperature_unit": "F",
            "mode_switches": true,
            "hsm": true,
            "debug": false,
            "programmable_buttons": [
                "97",
                "98"
            ],
            "excluded_capabilities": {
                "HUBITAT-DEVICE-ID-1": [
                    "Switch",
                    "TemperatureMeasurement"
                ]
            },
            "excluded_attributes": {
                "HUBITAT-DEVICE-ID-1": [
                    "power",
                    "humidity"
                ]
            },
            "logFile": {
                "enabled": true,
                "path": "",
                "file": "",
                "compress": true,
                "keep": 5,
                "size": "10m"
            }
        },
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        }
    ]
}```

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.0.4
* **Homebridge Config UI X Version**: 4.18.0
* **Operating System**: Raspbian 
* **Process Supervisor**:  hb-service 


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by oznu** [comment]
Pleases try uninstalling and reinstalling:

https://github.com/oznu/homebridge-config-ui-x#1-errors-during-installation

**Comment by sethfox** [comment]
That fixed it, thank you!
