### ISSUE TITLE
problem with update v4.18.0

### ISSUE THREAD

**Issue by warz1017** [oznu/homebridge-config-ui-x#670]
**Describe Your Problem:**

i have update my plugin Homebridge config ui x to v4.18.0 version but since this update I have some error message in the logs
**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```this error message;

5/8/2020, 9:54:23 PM] Error loading platform requested in your config.json at position 4
[5/8/2020, 9:54:23 PM] Error: The requested platform 'ZP' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
```
 Error: The requested platform 'ZP' was not registered by any plugin.
```

This plugin is missing. You may need to re-install it.
