### ISSUE TITLE
Error after upgrade homebridge-config-ui-x  to 1.1.0 

### ISSUE THREAD

**Issue by BartoszGan** [oznu/homebridge-config-ui-x#702]
Node.js: v11.0.0
Npm: v6.14.5

Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:81:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:117:20)
    at new Cipheriv (internal/crypto/cipher.js:226:22)
    at Object.createCipheriv (crypto.js:108:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapCrypto.ts:90:25)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:553:33)
    at HAPServer._this._handlePairVerify (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:515:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by oznu** [comment]
This is not a UI error, but updating your Node.js version will probably fix this.

**Comment by oznu** [comment]
Ok so this is a bit strange, but Node.js 10.17.0 (the minimum version Homebridge requires) is actually a newer release than 11.0.0. 

You will need to be on Node.js 11.2.0 or later.

**Comment by oznu** [comment]
This warning has been added to the release notes. Thanks for pointing out the issue.
https://github.com/homebridge/homebridge/releases/tag/1.1.0
