### ISSUE TITLE
accessories tab missing

### ISSUE THREAD

**Issue by lowrisk75** [oznu/homebridge-config-ui-x#72]
I already have the homebridge-config-UI-x but no accessories tab.

I added the template to the config 
```
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": false
    }
```
but then have the following error : 
```
 [2018-4-2 10:30:38] [Config] Using Form Authentication
homebridge_1  | Error: listen EADDRINUSE :::8080
homebridge_1  |     at Object._errnoException (util.js:1022:11)
homebridge_1  |     at _exceptionWithHostPort (util.js:1044:20)
homebridge_1  |     at Server.setupListenHandle [as _listen2] (net.js:1367:14)
homebridge_1  |     at listenInCluster (net.js:1408:12)
homebridge_1  |     at Server.listen (net.js:1492:7)
homebridge_1  |     at HomebridgeConfigUi.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/src/index.ts:42:17)
homebridge_1  |     at Generator.next (<anonymous>)
homebridge_1  |     at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/index.js:4:58)
homebridge_1  |     at <anonymous>
homebridge_1  | -U /homebridge -P /homebridge/node_modules

```

If I manually change the URL to http://xx.xx.xx.xx:8080/accessories
the page will load but with zero accessories or rooms

**Comment by oznu** [comment]
Hi @lowrisk75,

Please see:

https://github.com/oznu/docker-homebridge#optional-settings

> `-e HOMEBRIDGE_INSECURE=1` - Start homebridge in insecure mode using the -I flag.

and

https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-UI-with-Docker

**Comment by lowrisk75** [comment]
thank you.
