### ISSUE TITLE
config not assigned

### ISSUE THREAD

**Issue by Binog** [oznu/homebridge-config-ui-x#729]
**Describe The Bug:**
Sinne last update I get the following error/crash-report:
Hey,recently I have it on a pi zero: see logs

I did not change a thing in the config

**To Reproduce:**
nothing special

**Expected behavior:**
not such an eroor.

**Logs:**
Error loading platform requested in your config.json at position 1
**Error: The requested platform 'config' was not registered by any plugin.**
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at config.platforms.forEach (/usr/local/lib/node_modules/homebridge/src/server.ts:386:37)
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
homebridge@1.service: Succeeded.

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
 "platforms": [
        {
            "name": "config",
            "port": 8084,
            "auth": "none",
            "theme": "auto",
            "restart": "sudo -n systemctl restart homebridge@1",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "de",
            "sudo": true,
            "debug": false,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge@1"
            },
            "accessoryControl": {
                "debug": false
            },
            "platform": "config"
        },
```

**Environment:**

* **Node.js Version**: v10.20.1
* **NPM Version**: v6.14.5
* **Homebridge Version**: 1.1.0
* **Homebridge Config UI X Version**: 4.21.0
* **Operating System**: Raspbian 
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
The UI package is missing. Reinstall it.

https://github.com/oznu/homebridge-config-ui-x#1-errors-during-installation

**Comment by Binog** [comment]
Thank You !! That was it !
