### ISSUE TITLE
Upgrade to last version fails

### ISSUE THREAD

**Issue by sorriso93** [oznu/homebridge-config-ui-x#747]
**Describe The Bug:**
upgrade to 4.22 or 4.23 failes

**To Reproduce:**
simply upgrade by config-uix interface and also from sudo cmd line

**Expected behavior:**

**Logs:**
[19/06/2020, 13:07:03] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
[19/06/2020, 13:07:23] [HB Supervisor] OS: Linux 4.19.118-v7l+ arm
[19/06/2020, 13:07:23] [HB Supervisor] Node.js v13.5.0 /usr/local/bin/node
[19/06/2020, 13:07:23] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[19/06/2020, 13:07:23] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[19/06/2020, 13:07:23] [HB Supervisor] Starting Homebridge with extra flags: -I
[19/06/2020, 13:07:23] [HB Supervisor] Started Homebridge v1.1.1 with PID: 12205
[19/06/2020, 13:07:23] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: No valid exports main found for '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/common/decorators/core/injectable.decorator.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}

```json
config.json is ok on 4.21
```
**Environment:**

* **Node.js Version**: v13.5.0
* **NPM Version**: 6.13.4
* **Homebridge Version**:  1.1.1
* **Homebridge Config UI X Version**: 4.21
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/releases/tag/4.22.0 (which you may have missed if you started on 4.21 and went straight to 4.23 sorry)...

![image](https://user-images.githubusercontent.com/3979615/85126804-84f63d00-b271-11ea-9ee1-a40bff096d4a.png)

Upgade Node.js and you should be right. 

```
sudo curl -Lf# "https://unofficial-builds.nodejs.org/download/release/v12.18.1/node-v12.18.1-linux-armv6l.tar.gz" | sudo tar xzf - -C /usr/local --strip-components=1 --no-same-owner
```

**Comment by sorriso93** [comment]
@oznu  now it is ok.
I didn't see the alert in 4.21, many thanks

**Comment by oznu** [comment]
Great!
