### ISSUE TITLE
Web UI Refused to Connect after Updating

### ISSUE THREAD

**Issue by biocross** [oznu/homebridge-config-ui-x#796]
Hello!

Firstly, thank you for the great work on this plugin. I just upgraded to the latest version of the plugin on my Raspberry Pi, and seem to be facing an issue where the Web UI if `refusing to connect`

**Describe The Bug:**
The Homebridge UI just prompted me for an update from version **4.18.0** to the latest (**4.24.0**). After clicking update (and then restart) on the Web UI, I get the error: `the server refused to connect`. I was using the   http://<ip of the pi>:8541 URL to connect to the UI.

**Expected behavior:**
The Web UI should work.

**What I've tried**
After the plugin stopped working, I've since tried:
- Using the port **8080** (as mentioned in the current README of the project) to connect. Didn't work.
- Upgrading **homebridge** to the latest version (from **1.0.4** -> **1.1.1**)
- Uninstalling and installing this package `homebridge-config-ui-x` again.
- Tried adding the platform `config` to my homebrige `config.json`. After adding this explicitly, I now get the error mentioned in the logs below when running `homebridge`:

**Logs:**
```
[02/08/2020, 10:29:03] [HB Supervisor] OS: Linux 4.19.58-v7+ arm
[02/08/2020, 10:29:03] [HB Supervisor] Node.js v13.5.0 /usr/local/bin/node
[02/08/2020, 10:29:03] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[02/08/2020, 10:29:03] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[02/08/2020, 10:29:03] [HB Supervisor] Starting Homebridge with extra flags: -I
[02/08/2020, 10:29:04] [HB Supervisor] Started Homebridge v1.1.1 with PID: 24952
[02/08/2020, 10:29:06] [HB Supervisor] ERROR: The user interface threw an unhandled error
/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/common/decorators/core/injectable.decorator.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
[02/08/2020, 10:29:06] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
```

**Homebridge Config:**

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "--",
    "port": 51826,
    "pin": "--"
  },
  "accessories": [
    {
      "accessory": "ServoSwitch",
      "name": "Lights"
    }
  ],
  "platforms": [
    {
      "platform": "BelkinWeMo",
      "name": "WeMo Platform"
    },
    {
      "platform": "config",
      "name": "Config",
      "port": 8541,
      "sudo": false
    }
  ]
}
```

**Screenshots:**
<img width="809" alt="Screenshot 2020-08-02 at 6 01 21 PM" src="https://user-images.githubusercontent.com/840512/89120598-3c75a480-d4ea-11ea-9339-7f0df08fee7f.png">

**Environment:**

* **Node.js Version**: v13.5.0
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.1.1
* **Homebridge Config UI X Version**: 4.24.0
* **Operating System**: Raspbian (Linux 4.19.58-v7+ arm)
* **Process Supervisor**: pm2

**Comment by oznu** [comment]
Upgrade Node.js.

13.0.0 to 13.6.0 have a bug that prevent a certain dependency from loading. Fixed in 13.7.0 or later (or 10.17.0 or later).

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/releases/tag/4.22.0

**Comment by biocross** [comment]
Thank you so much for the quick reply! Upgrading Node to 14.7.0 fixed the issue
