### ISSUE TITLE
Getting this error dont know why

### ISSUE THREAD

**Issue by roberkane212** [oznu/homebridge-config-ui-x#817]
[HB Supervisor] Starting Homebridge with extra flags: -I
[8/16/2020, 22:29:17] [HB Supervisor] Started Homebridge v1.1.2 with PID: 1853
[8/16/2020, 22:29:19] [HB Supervisor] ERROR: The user interface threw an unhandled error
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at extendStatics (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/rxjs/internal/observable/ConnectableObservable.js:7:16)
    at __extends (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/rxjs/internal/observable/ConnectableObservable.js:10:9)
    at /usr/lib/node_modules/homebridge-config-ui-x/node_modules/rxjs/internal/observable/ConnectableObservable.js:22:5
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/rxjs/internal/observable/ConnectableObservable.js:59:2)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
[8/16/2020, 22:29:19] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
[8/16/2020, 22:29:29] [HB Supervisor] OS: Linux 4.19.75-v7+ arm
[8/16/2020, 22:29:29] [HB Supervisor] Node.js v12.18.3 /usr/bin/node
[8/16/2020, 22:29:29] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[8/16/2020, 22:29:29] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[8/16/2020, 22:29:29] [HB Supervisor] Starting Homebridge with extra flags: -I
[8/16/2020, 22:29:29] [HB Supervisor] Started Homebridge v1.1.2 with PID: 2004
[8/16/2020, 22:29:31] [HB Supervisor] ERROR: The user interface threw an unhandled error

**Comment by oznu** [comment]
```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by roberkane212** [comment]
@oznu thank you so much!!!!

**Comment by roberkane212** [comment]
@oznu only works for a small moment when I restart pi then doesn’t work anymore on config ui x web browser nor does accessories work in HomeKit

**Comment by oznu** [comment]
That sounds like your SD card is on the way out / corrupted.

**Comment by roberkane212** [comment]
@oznu do you know if it’s possible to transfer homebridge ui x to new sd card? Or should I just start over?

**Comment by oznu** [comment]
You can take a backup:

https://github.com/homebridge/homebridge/wiki/Backup-and-Restore
