### ISSUE TITLE
Can't start HB anymore

### ISSUE THREAD

**Issue by Bankaifan** [oznu/homebridge-config-ui-x#83]
I get this error:

[2018-4-16 08:24:56] [Config] Using Form Authentication
Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at UiServer.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/src/server.ts:39:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/server.js:4:58)
    at <anonymous>

This is the full output
pi@raspberrypi:~ $ sudo homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-16 08:24:45] Loaded plugin: homebridge-broadband
[2018-4-16 08:24:47] Registering accessory 'homebridge-broadband.Broadband'
[2018-4-16 08:24:47] ---
[2018-4-16 08:24:47] Loaded plugin: homebridge-config-ui-x
[2018-4-16 08:24:47] Registering platform 'homebridge-config-ui-x.config'
[2018-4-16 08:24:47] ---
[2018-4-16 08:24:47] Loaded plugin: homebridge-fritz
[2018-4-16 08:24:48] Registering platform 'homebridge-fritz.Fritz!Box'
[2018-4-16 08:24:48] ---
[2018-4-16 08:24:48] Loaded plugin: homebridge-mi-flower-care
[2018-4-16 08:24:49] Registering accessory 'homebridge-mi-flower-care.mi-flower-care'
[2018-4-16 08:24:49] ---
[2018-4-16 08:24:50] Loaded plugin: homebridge-people
[2018-4-16 08:24:50] Registering platform 'homebridge-people.People'
[2018-4-16 08:24:50] Registering accessory 'homebridge-people.PeopleAccessory'
[2018-4-16 08:24:50] Registering accessory 'homebridge-people.PeopleAllAccessory'
[2018-4-16 08:24:50] ---
[2018-4-16 08:24:50] Loaded plugin: homebridge-philipstv-x
[2018-4-16 08:24:50] Registering accessory 'homebridge-philipstv.PhilipsTV'
[2018-4-16 08:24:50] ---
[2018-4-16 08:24:50] Loaded plugin: homebridge-raspberrypi-temperature
[2018-4-16 08:24:50] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[2018-4-16 08:24:50] ---
[2018-4-16 08:24:50] Loaded plugin: homebridge-wol
[2018-4-16 08:24:50] Registering accessory 'homebridge-wol.NetworkDevice'
[2018-4-16 08:24:50] ---
[2018-4-16 08:24:51] Loaded plugin: homebridge-xiaomi-roborock-vacuum
[2018-4-16 08:24:51] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[2018-4-16 08:24:51] ---
[2018-4-16 08:24:51] Loaded config.json with 8 accessories and 2 platforms.
[2018-4-16 08:24:51] ---
[2018-4-16 08:24:51] Loading 2 platforms...
[2018-4-16 08:24:51] [Config] Initializing config platform...
[2018-4-16 08:24:51] [Config] Spawning homebridge-config-ui-x with PID 2783
[2018-4-16 08:24:51] [Fritz!Box] Initializing Fritz!Box platform...
[2018-4-16 08:24:51] Loading 8 accessories...
[2018-4-16 08:24:51] [Daniels PC] Initializing NetworkDevice accessory...
[2018-4-16 08:24:51] [MacBook] Initializing NetworkDevice accessory...
[2018-4-16 08:24:51] [Pi Temp] Initializing RaspberryPiTemperature accessory...
[2018-4-16 08:24:51] [TV] Initializing PhilipsTV accessory...
[2018-4-16 08:24:51] [TV] Model year: 2016
[2018-4-16 08:24:51] [TV] API version: 6
[2018-4-16 08:24:51] [Broadband] Initializing Broadband accessory...
[2018-4-16 08:24:51] [Staubsauger] Initializing XiaomiRoborockVacuum accessory...
[2018-4-16 08:24:51] [Birkenfeige] Initializing mi-flower-care accessory...
[2018-4-16 08:24:51] [Kaffee] Initializing mi-flower-care accessory...
[2018-4-16 08:24:51] [MacBook] NetworkDevice "MacBook" (192.168.178.23) went from status "Offline" to "Online"
[2018-4-16 08:24:52] [Fritz!Box] Fritz!Box platform login successful
[2018-4-16 08:24:52] [Fritz!Box] Discovering accessories
[2018-4-16 08:24:53] [Staubsauger] ERROR, miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2018-4-16 08:24:56] [Config] Using Form Authentication
Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at UiServer.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/src/server.ts:39:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/server.js:4:58)
    at <anonymous>

**Comment by oznu** [comment]
```Error: listen EADDRINUSE :::8080``` means another process is running on the same port.

Try run this to make sure there aren't any stale processes:

```
sudo killall homebridge
sudo killall homebridge-config-ui-x
```

**Comment by oznu** [comment]
3.5.3 will prevent rouge homebridge-config-ui-x processes.
