### ISSUE TITLE
Installing Homebridge using your instructions causes Homebridge to continuously restart

### ISSUE THREAD

**Issue by SearchwareSolutions** [oznu/homebridge-config-ui-x#840]
I had a prior installation of Homebridge on my Mac mini running macOS Mojave 10.14.6. However, I wanted to update the installation to the latest version and found your homebridge-config-ui-x and wanted to use this interface. I completely uninstalled Homebridge and deleted all related directories. I then used your instructions to reinstall, including homebridge-config-ui-x as well as setting Homebridge to run as a service.

Unfortunately, since that time, Homebridge simply continuously terminates and restarts. The logs show the following repeated loop:

```
[9/6/2020, 8:54:25 PM] [Config] Homebridge Config UI X v4.27.1 is listening on :: port 8581
[9/6/2020, 8:54:25 PM] [Config] Error: listen EADDRINUSE: address already in use :::8581
[9/6/2020, 8:54:25 PM] [Config] Another process or service on this host is using port 8581.
[9/6/2020, 8:54:25 PM] [Config] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[9/6/2020, 8:54:25 PM] [Config] Ending process now.
[9/6/2020, 8:54:28 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[9/6/2020, 8:54:33 PM] [HB Supervisor] Restarting Homebridge...
[9/6/2020, 8:54:33 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[9/6/2020, 8:54:33 PM] [HB Supervisor] Started Homebridge v1.1.3 with PID: 2666
[9/6/2020, 8:54:34 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/6/2020, 8:54:34 PM] ---
[9/6/2020, 8:54:34 PM] Loaded plugin: homebridge-config-ui-x@4.27.1
[9/6/2020, 8:54:34 PM] Registering platform 'homebridge-config-ui-x.config'
[9/6/2020, 8:54:34 PM] ---
[9/6/2020, 8:54:34 PM] Loading 1 platforms...
[9/6/2020, 8:54:34 PM] [Config] Initializing config platform...
[9/6/2020, 8:54:34 PM] [Config] Running in Service Mode
[9/6/2020, 8:54:34 PM] Error: EACCES: permission denied, open '/Users/scrick/.homebridge/persist/AccessoryInfo.0EC87953C502.json'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1362:35)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:476:16)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:277:14)
    at AccessoryInfo.save (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/model/AccessoryInfo.ts:179:26)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:912:25)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:192:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:164:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:163:5)
[9/6/2020, 8:54:34 PM] Got SIGTERM, shutting down Homebridge...
```

I am unable to figure this out. Any help would be appreciated. Thank you!

**Comment by oznu** [comment]
> I had a prior installation of Homebridge on my Mac mini running macOS Mojave 10.14.6. 

You still have another installation running. The error in the logs is due to another instance running in the same port.

See https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-macOS#remove-existing-homebridge-service

Then re-install as per wiki instructions.
