### ISSUE TITLE
Homebridge UI Not Running

### ISSUE THREAD

**Issue by Schachjj** [oznu/homebridge-config-ui-x#857]
I am at a loss here! I have been fighting with home bridge (MacOS) for a couple of weeks now. It appears to be running in the background but I can't get the UI to load and my devices are all reporting offline. I'm new here so any help is appreciated!

**Comment by Schachjj** [comment]
Hit return too quickly! And when I run hb-service stop, then type home bridge - it seems to get hung up on the last step:

jessieschachleiter@macbook-pro ~ % sudo hb-service status
ℹ Testing hb-service is running on port 8581...
✖ Homebridge UI Not Running
jessieschachleiter@macbook-pro ~ % sudo hb-service stop
Password:
ℹ Stopping Homebridge Service...
/Library/LaunchDaemons/com.homebridge.server.plist: Operation now in progress
✔ Homebridge Stopped
jessieschachleiter@macbook-pro ~ % homebridge
[9/24/2020, 11:39:12 AM] Loaded config.json with 0 accessories and 5 platforms.
[9/24/2020, 11:39:12 AM] ---
[9/24/2020, 11:39:12 AM] Loaded plugin: homebridge-config-ui-x@4.27.1
[9/24/2020, 11:39:12 AM] Registering platform 'homebridge-config-ui-x.config'
[9/24/2020, 11:39:12 AM] ---
[9/24/2020, 11:39:13 AM] Loaded plugin: homebridge-harmony@1.3.12
[9/24/2020, 11:39:13 AM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[9/24/2020, 11:39:13 AM] ---
[9/24/2020, 11:39:13 AM] Loaded plugin: homebridge-harmonyhub@0.3.0-alpha.2
[9/24/2020, 11:39:14 AM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[9/24/2020, 11:39:14 AM] ---
[9/24/2020, 11:39:15 AM] Loaded plugin: homebridge-ring@9.9.0
[9/24/2020, 11:39:15 AM] Registering platform 'homebridge-ring.Ring'
[9/24/2020, 11:39:15 AM] ---
[9/24/2020, 11:39:15 AM] Loaded plugin: homebridge-roku-tv-plugin@1.0.9
[9/24/2020, 11:39:15 AM] Registering platform 'homebridge-roku-tv-plugin.RokuTV'
[9/24/2020, 11:39:15 AM] ---
[9/24/2020, 11:39:15 AM] Loaded plugin: homebridge-samsung-tizen@4.3.3
[9/24/2020, 11:39:15 AM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[9/24/2020, 11:39:15 AM] ---
[9/24/2020, 11:39:15 AM] Loading 5 platforms...
[9/24/2020, 11:39:15 AM] [Config] Initializing config platform...
[9/24/2020, 11:39:15 AM] [Config] Spawning homebridge-config-ui-x with PID 3794
[9/24/2020, 11:39:15 AM] [Ring] Initializing Ring platform...
[9/24/2020, 11:39:15 AM] [RokuTV] Initializing RokuTV platform...
[9/24/2020, 11:39:15 AM] [Harmony Hub] Initializing HarmonyHubWebSocket platform...
[9/24/2020, 11:39:15 AM] [Harmony Hub] HarmonyPlatform Init
[9/24/2020, 11:39:15 AM] [SamsungTizen] Initializing SamsungTizen platform...
[9/24/2020, 11:39:15 AM] [Ring] Configuring cached accessory a6491e17-6b83-4680-8b8c-1eadb1dba1b4 Front Door
[9/24/2020, 11:39:15 AM] [Ring] Configuring cached accessory 49c52896-1471-44d1-9354-10ade9ecdfb5 Entry
[9/24/2020, 11:39:15 AM] [Ring] Configuring cached accessory 52e8236a-cb6e-421e-bd46-92c07bb2a7f1 Basement
[9/24/2020, 11:39:15 AM] [Harmony Hub] DidFinishLaunching
[9/24/2020, 11:39:15 AM] [Harmony Hub] (Harmony Hub)INFO - Loading activities...
Setup Payload:
X-HM://0024X081HMGGK
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 874-64-373 │     
    └────────────┘     
                       
[9/24/2020, 11:39:15 AM] Homebridge is running on port 51456.
[9/24/2020, 11:39:15 AM] Family Room TV is running on port 57466.
[9/24/2020, 11:39:15 AM] Please add [Family Room TV] manually in Home app. Setup Code: 874-64-373
[9/24/2020, 11:39:16 AM] [Harmony Hub] (Harmony Hub)INFO - configuring Main TV Service
[9/24/2020, 11:39:16 AM] [Harmony Hub] (Harmony Hub)WARNING - No main Activity that match config file found, default to first one
[9/24/2020, 11:39:16 AM] [Harmony Hub] (Harmony Hub)INFO - Configuring Main Activity Watch Bluray
[9/24/2020, 11:39:17 AM] [Ring] Configuring 1 cameras and 3 devices for location "Mason" - locationId: 803572bb-b722-497c-6b32-60036880805c
[9/24/2020, 11:39:18 AM] [Config] Homebridge Config UI X v4.27.1 is listening on :: port 8581

**Comment by geoffreyspencer** [comment]
I am having the exact same issue. Is there any solution??

**Comment by geoffreyspencer** [comment]
Here is part of the error log from HomeBridge

[9/26/2020, 4:32:12 PM] Error: Cannot update txt of service which is not announced yet. Received unannounced for service Homebridge 793B AF95._hap._tcp.local.
    at Responder.handleServiceRecordUpdate (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/Responder.ts:410:13)
    at CiaoService.emit (events.js:198:13)
    at Timeout.txtTimer.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/CiaoService.ts:461:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[9/26/2020, 4:32:14 PM] Got SIGTERM, shutting down Homebridge...
[9/26/2020, 4:32:14 PM] ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:354:13)
    at MDNSServer.sendOnAllNetworks (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:274:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:235:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:155:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at unrefdHandle (timers.js:520:7)
    at Timer.processTimers (timers.js:222:12)
[9/26/2020, 4:32:19 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[9/26/2020, 4:32:24 PM] [HB Supervisor] Restarting Homebridge...
[9/26/2020, 4:32:24 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[9/26/2020, 4:32:24 PM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 2670
[9/26/2020, 4:32:27 PM] Loaded config.json with 0 accessories and 8 platforms.
[9/26/2020, 4:32:27 PM] ---

**Comment by dziarski-hwat** [comment]
Did you do any updates with homebrew recently? Yesterday it updated node to 14.13.1 and the UI stopped loading.

Editing /Library/LaunchDaemons/com.homebridge.server.plist and replacing the path to node to /usr/local/bin/node fit it for me and homebrigde is loading again and all accessories work again.

**Comment by jbinder6342** [comment]
I had the same issue as I had updated to node 18.5.0 and rpm v 8.12.1 (brew installed).  

setting com.homebridge.server.plist -> ProgramArguments to  " <string>/usr/local/Cellar/node/18.5.0/bin/node</string>" fixed my issue as well.
