### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by pax0707** [oznu/homebridge-config-ui-x#86]
This can happen 1-3 times a day.

Is it something obvious or should I leave it debugging?

```
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:713:20)
    at ChildProcess.target.send (internal/child_process.js:597:19)
    at Timeout.setInterval [as _onTimeout] (C:\Users\pax07\node_modules\homebridge-config-ui-x\src\index.ts:60:10)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

**Comment by oznu** [comment]
3.5.5 should fix this problem.
