### ISSUE TITLE
config-ui-x for jailbroken iPhone?

### ISSUE THREAD

**Issue by Fede-z8na** [oznu/homebridge-config-ui-x#885]
Homebridge works fine using an old jailbroken iPhone, however trying to install your Plugin returns the following errors. (I suppose because it wasn't developed for this platform).
Would it be possible to make it compatible in future?

**Logs:**

```
iPhone-6S:~ root# npm install -g --unsafe-perm homebridge-config-ui-x@latest
/usr/bin/homebridge-config-ui-x -> /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
/usr/bin/hb-service -> /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js

> node-pty-prebuilt-multiarch@0.9.0 install /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=14.13.1 runtime=node arch=arm64 libc= platform=darwin)
Traceback (most recent call last):
  File "/usr/share/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2214, in GenerateOutput
    writer.Write(qualified_target, base_path, output_file, spec, configs,
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 818, in Write
    self.WriteSources(
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1218, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 483, in GetCflags
    sdk_root = self._SdkPath()
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 452, in _SdkPath
    return self._XcodeSdkPath(sdk_root)
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 456, in _XcodeSdkPath
    sdk_path = self._GetSdkVersionInfoItem(sdk_root, 'Path')
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 439, in _GetSdkVersionInfoItem
    return GetStdoutQuiet(['xcodebuild', '-version', '-sdk', sdk, infoitem])
  File "/usr/share/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1323, in GetStdoutQuiet
    job = subprocess.Popen(cmdlist, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xcodebuild'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 20.0.0
gyp ERR! command "/usr/bin/node" "/usr/share/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v14.13.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Environment:**

* **Node.js Version**:  v14.13.1
* **NPM Version**:  6.14.8
* **Homebridge Version**:  1.2.3
* **Homebridge Config UI X Version**: 4.28.1
* **Operating System**: iOS 14.0.1
* **Jailbreak**: Odysseyra1n

**Comment by oznu** [comment]
You need to install `xcode-tools` or equivalent to compile the native c++ modules.

**Comment by oznu** [comment]
Thanks for xcode 12.2 we now have pre-compiled binaries for `darwin-arm64` and `darwin-arm` which may also work on your jailbroken iPhone.
