### ISSUE TITLE
homebridge-config-ui-x/package.json: fs.readFileSync is not a function

### ISSUE THREAD

**Issue by rgerr** [oznu/homebridge-config-ui-x#91]
`Error: /usr/lib/node_modules/homebridge-config-ui-x/package.json: fs.readFileSync is not a function`

After installing with and without --unsafe-perm, after updating the config and starting up Homebridge, I am getting this error.

**Comment by oznu** [comment]
Hi,

Can you provide details of your setup? Node version, npm version, and the full homebridge log output. Thanks.

**Comment by rgerr** [comment]
Node v9.11.1
Npm v5.6.0

Homebridge output below:

/usr/lib/node_modules/homebridge-config-ui-x/node_modules/jsonfile/index.js:61
    var content = fs.readFileSync(file, options)
                     ^
TypeError: /usr/lib/node_modules/homebridge-config-ui-x/package.json: fs.readFileSync is not a function
    at Object.readFileSync (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/jsonfile/index.js:61:22)
    at new HomebridgeUI (/usr/lib/node_modules/homebridge-config-ui-x/src/hb.ts:39:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/src/hb.ts:294:19)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

**Comment by oznu** [comment]
This is pretty strange. There were some issues with the 3.6.2 release which may have caused this, are you able to try the new version I just pushed out? 3.6.3-3.

```
sudo npm uninstall -g homebridge-config-ui-x
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

This newer version ships with an updated version of the `fs-extra` package.
