### ISSUE TITLE
SyntaxError in uuid dependency

### ISSUE THREAD

**Issue by dominicegginton** [oznu/homebridge-config-ui-x#959]
**Describe The Bug:**

After following the installtion guide for homebridge and homebridge-config-ui-x font [here](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux#configuration-reference) the config ui fails to stat due to a sytax errror. I have included logs and my config.json.

**Logs:**

```
[11/17/2020, 12:11:22 PM] [HB Supervisor] OS: Linux 4.15.0-123-generic x64
[11/17/2020, 12:11:22 PM] [HB Supervisor] Node.js v14.15.1 /usr/bin/node
[11/17/2020, 12:11:22 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[11/17/2020, 12:11:22 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[11/17/2020, 12:11:22 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[11/17/2020, 12:11:22 PM] [HB Supervisor] Started Homebridge v1.2.1 with PID: 4691
[11/17/2020, 12:11:22 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/common/decorators/core/injectable.decorator.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[11/17/2020, 12:11:22 PM] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
```

**Homebridge Config:**

``` json
{
    "bridge": {
        "name": "Homebridge DCAD",
        "username": "0E:59:E9:96:DC:AD",
        "port": 51791,
        "pin": "667-06-431"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: 14.15.1
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.1
* **Homebridge Config UI X Version**: 4.33.0
* **Operating System**: Ubuntu
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Did you previously have Node.js or Homebridge installed before following the guide?

**Comment by oznu** [comment]
I suspect you did, based on the Homebridge version you have installed.

Can you do this to clean things up?

Step 1. Remove the service:

```
sudo hb-service uninstall
```

Step 2: Remove Node.js entirely:

**:warning: [This script](https://gist.githubusercontent.com/oznu/312b54364616082c3c1e0b6b02351f0e/raw/remove-node.sh) to removes all copies of Node.js, Homebridge, and plugins and other npm modules installed on your system.**

```
sudo curl -fL https://git.io/JfFFM | sudo bash
```

Step 3: Follow [the guide](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux) again.

**Comment by dominicegginton** [comment]
@oznu you were right it looks like a previous version of homebridge was casusing the issue. The fresh install of node and homebridge works thank you for your help 😄
