### ISSUE TITLE
Ui port problem

### ISSUE THREAD

**Issue by sanskardhanda** [oznu/homebridge-config-ui-x#972]
**Describe The Bug:**
Ui port problem

**To Reproduce:**
Just reinstalled homebridge and able to see error when I type homebridge in terminal. 

**Expected behavior:**
Homebridge doesn't work

**Logs:**

```Show the Homebridge / Homebridge Config UI X logs here.
```[11/26/2020, 1:22:27 PM] Loaded config.json with 0 accessories and 2 platforms.
[11/26/2020, 1:22:27 PM] ---
[11/26/2020, 1:22:27 PM] Loaded plugin: homebridge-config-ui-x@4.34.0
[11/26/2020, 1:22:27 PM] Registering platform 'homebridge-config-ui-x.config'
[11/26/2020, 1:22:27 PM] ---
[11/26/2020, 1:22:27 PM] Loaded plugin: homebridge-ewelink@3.15.0
[11/26/2020, 1:22:27 PM] Registering platform 'homebridge-ewelink.eWeLink'
[11/26/2020, 1:22:27 PM] ---
[11/26/2020, 1:22:27 PM] Loading 2 platforms...
[11/26/2020, 1:22:27 PM] [Config] Initializing config platform...
[11/26/2020, 1:22:27 PM] [Config] Spawning homebridge-config-ui-x with PID 3871
[11/26/2020, 1:22:27 PM] [eWeLink] Initializing eWeLink platform...
[11/26/2020, 1:22:27 PM] [eWeLink] Plugin [v3.15.0] initialised. Syncing with eWeLink...
Setup Payload:
X-HM://002462EEENB4C
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 422-16-294 │     
    └────────────┘     
                       
[11/26/2020, 1:22:27 PM] Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:84:21)
    at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:236:22)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:976:18)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:192:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:164:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:163:5)
[11/26/2020, 1:22:27 PM] Got SIGTERM, shutting down Homebridge...
^[[B^[[B[11/26/2020, 1:22:29 PM] [Homebridge UI] Homebridge Config UI X v4.34.0 is listening on :: port 8581
[11/26/2020, 1:22:30 PM] [Homebridge UI] Error: listen EADDRINUSE: address already in use :::8581
[11/26/2020, 1:22:30 PM] [Homebridge UI] Another process or service on this host is using port 8581.
[11/26/2020, 1:22:30 PM] [Homebridge UI] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[11/26/2020, 1:22:30 PM] [Homebridge UI] Ending process now.


**Homebridge Config:**

```json
Show your homebridge config.json here
```{
    "bridge": {
        "name": "Homebridge 991D",
        "username": "0E:0E:AC:22:99:1D",
        "port": 51826,
        "pin": "422-16-294"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "eWeLink",
            "countryCode": "country code",
            "username": "username",
            "password": "password",
            "debug": false,
            "debugReqRes": false,
            "disableHTTPRefresh": false,
            "disablePlugin": false,
            "inUsePowerThreshold": 0,
            "lowBattThreshold": 25,
            "sensorTimeDifference": 120,
            "hideZBLDPress": false,
            "groups": [
                {
                    "operationTime": 100
                }
            ],
            "bridgeSensors": [
                {
                    "sensorTimeLength": 60
                }
            ],
            "platform": "eWeLink"
        }
    ]
}

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Node.js Version**: 14.5.1
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.1.6
* **Homebridge Config UI X Version**:4.34.0
* **Operating System**: macOS
* **Process Supervisor**: hb-service


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by oznu** [comment]
> [11/26/2020, 1:22:27 PM] Error: listen EADDRINUSE: address already in use :::51826
at Server.setupListenHandle [as _listen2] (net.js:1318:16)

You have another instance of Homebridge running. If you've set it up as a service then you will need to stop it before running homebridge manually in the terminal.

**Comment by sanskardhanda** [comment]
No other instance is running

**Comment by sanskardhanda** [comment]
I am running homebridge only on macOS and I did complete reinstall of Mac yesterday

**Comment by oznu** [comment]
It almost certainly is, otherwise you wouldn't get that error.

**Comment by oznu** [comment]
Stop anything processes you have running in a terminal window, then see what happens when you go to http://localhost:8581?

**Comment by sanskardhanda** [comment]
I am getting this error after updating nodejs

**Comment by oznu** [comment]
Could you let me know the results of this: 

https://github.com/oznu/homebridge-config-ui-x/issues/972#issuecomment-734141814

**Comment by axello** [comment]
### Added for posterity.
For me, the situation also happened, with homebridge 1.1.7 and "Homebridge Config UI X" v4.36.0.
when I looked with netstat, sometimes there was an extra Homebridge Config UI X spawned. 

I am using pm2 to start the node modules, but am otherwise an npm noob.

As it turned out, I also had multiple installations of homebridge AND Homebridge Config UI X. (!)

I had versions installed due to various blogposts, so had used 
1. `sudo npm install <package>`
which installs at `/usr/lib/node_modules` as root
2. `npm install -g <package>`
which installs at `~/.npm-global/lib/node_modules/ as user, and
3. while `npm install <package>` 
which installs at `~/node_modules/ as user

I have removed all the versions except the ones in `~/.npm-global/lib/node_modules/` and this seems to work. 

When you install plugins using Homebridge Config UI X, it installs them however in /usr/lib/node_modules, but as it seems to work, I leave it like that.

Hope this helps anyone.

**Comment by oznu** [comment]
See this wiki article for instructions on how to clean up multiple Node.js / Homebridge installations and get back to a "standard" and "supported" setup:

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux
