### ISSUE TITLE
Recovering my Homebridge it crashes  Homebridge Sin ejecutarse - Ver logs

### ISSUE THREAD

**Issue by Ludelag** [oznu/homebridge-config-ui-x#977]
2020-11-28 0:00:15] ====================
[2020-11-28 0:00:15] Loading 3 platforms...
[2020-11-28 0:00:15] [Config] Initializing config platform...
[2020-11-28 0:00:15] [Config] Running in Service Mode
[2020-11-28 0:00:15] [Shelly] Initializing Shelly platform...
[2020-11-28 0:00:15] Error loading platform requested in your config.json at position 3
[2020-11-28 0:00:15] Error: The requested platform 'webostv' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (C:\Users\delag\AppData\Roaming\npm\node_modules\homebridge\src\pluginManager.ts:224:15)
    at C:\Users\delag\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (C:\Users\delag\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:374:27)
    at Server.start (C:\Users\delag\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:153:29)
    at cli (C:\Users\delag\AppData\Roaming\npm\node_modules\homebridge\src\cli.ts:80:10)
    at Object.<anonymous> (C:\Users\delag\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.

**Comment by oznu** [comment]
> Error: The requested platform 'webostv' was not registered by any plugin.

Either remove that from your config or install the corresponding plugin.

**Comment by Ludelag** [comment]
Thank you
